---
title: "Week 2 Notes - Algorithmic Decision Making & Census Data"
date: "2025-09-15"
---

## Key Concepts Learned

-   R basics practice in RStudio
-   Types of algorithms
-   Types of Census Data vs ACS data
    -   Blocks data is only available for Decennial Census data
    -   Block Group data has large margins of error

## Coding Techniques

-   Lab0 Practice of R fundamentals and packages
-   Intro to tidycensus

## Questions & Challenges

-   With more reps, I hope to become more independent in my coding instead of having to refer to demo code

## Connections to Policy

-   When policymakers explore the use of algorithms, they need to ask themselves
    -   what proxy are they using?
    -   what are the possible blind spots?
    -   what are the resultant harms as well as potential guardrails?

## Reflection

-   It was really interesting to hear about the 2020 Census Innovation of Differential Privacy (adding mathematical noise as anomalies to protect respondents' privacy)
