project:
  type: website
  output-dir: docs

website:
  title: "Jed Chew - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      
      - text: Weekly Notes
        menu: 
        - href: weekly-notes/week-01-notes.qmd
        - href: weekly-notes/week-02-notes.qmd
        - href: weekly-notes/week-03-notes.qmd
        - href: weekly-notes/week-04-notes.qmd
        - href: weekly-notes/week-05-notes.qmd
        - href: weekly-notes/week-06-notes.qmd
        - href: weekly-notes/week-07-notes.qmd
          
      - text: Labs
        menu:
        - href: labs/lab_0/scripts/lab0_template.qmd
        - href: labs/lab_1/assignment1_template.qmd
        - href: labs/lab_2/assignment2_template.qmd
        
      - text: Side Hustles
        menu:
        - href: side-hustles/dataaxle.qmd
        - href: side-hustles/demographic_change.qmd
        - href: side-hustles/vacancy_land_use.qmd
        

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
