project:
  type: website
  output-dir: docs

website:
  title: "Jed Chew - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      
      - text: Weekly Notes
        menu: 
        - href: weekly-notes/week-01-notes.qmd
        - href: weekly-notes/week-02-notes.qmd
          
      - text: Labs
        menu:
        - href: labs/lab_0/scripts/lab0_template.qmd
        - href: labs/lab_1/assignment1_template.qmd
          

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
