project:
  type: website
  output-dir: docs

website:
  title: "Jed Chew - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Weekly Notes
        menu: 
        - href: weekly-notes/week-01-notes.qmd
        - text: week

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
