{
  "hash": "12593c281a5a7547480eb1c18167c2a9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Jed Chew\"\ndate: today\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\neditor: \n  markdown: \n    wrap: 80\n---\n\n## Assignment Overview\n\n**Learning Objectives:**\n\n-   Apply spatial operations to answer policy-relevant research questions\n\n-   Integrate census demographic data with spatial analysis\n\n-   Create publication-quality visualizations and maps\n\n-   Work with spatial data from multiple sources\n\n-   Communicate findings effectively for policy audiences\n\n--------------------------------------------------------------------------------\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable\npopulations (elderly + low-income) living far from hospitals?**\n\nYour analysis should identify counties that should be priorities for healthcare\ninvestment and policy intervention.\n\n### Required Analysis Steps\n\nComplete the following analysis, documenting each step with code and brief\nexplanations:\n\n#### Step 1: Data Collection (5 points)\n\nLoad the required spatial data:\n\n-   Pennsylvania county boundaries (from lecture data)\n\n-   Pennsylvania hospitals (from lecture data)\n\n-   Pennsylvania census tracts\n\n**Your Task:**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load spatial data\npa_counties <- st_read(\"data/Pennsylvania_County_Boundaries.shp\")\ndistricts <- st_read(\"data/districts.geojson\")\nhospitals <- st_read(\"data/hospitals.geojson\")\ncensus_tracts <- tracts(state = \"PA\", cb = TRUE, progress = FALSE)\nmetro_areas <- core_based_statistical_areas(cb = TRUE, progress = FALSE)\n\n# Standardize CRS\nhospitals <- st_transform(hospitals, st_crs(pa_counties))\ncensus_tracts <- st_transform(census_tracts, st_crs(pa_counties))\nmetro_areas <- st_transform(metro_areas, st_crs(pa_counties))\ndistricts <- st_transform(districts, st_crs(census_tracts))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check that all data loaded correctly\nggplot(pa_counties) +\n  geom_sf() +\n  labs(title = \"PA Counties\") +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(census_tracts) +\n  geom_sf() +\n  labs(title = \"PA Census Tracts\") +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-3-2.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(districts) +\n  geom_sf() +\n  labs(title = \"PA districts\") +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-3-3.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(hospitals) +\n  geom_sf() +\n  labs(title = \"Hospitals\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-3-4.png){width=672}\n:::\n:::\n\n\n**Questions to answer:**\n\n-   How many hospitals are in your dataset? – **223 hospitals**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(hospitals) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 223 features and 11 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -8960798 ymin: 4829916 xmax: -8334160 ymax: 5181077\nProjected CRS: WGS 84 / Pseudo-Mercator\nFirst 10 features:\n                  CHIEF_EXEC              CHIEF_EX_1\n1              Peter J Adamo               President\n2           Autumn DeShields Chief Executive Officer\n3               Shawn Parekh Chief Executive Officer\n4                DIANE HRITZ Chief Executive Officer\n5             Tim Harclerode Chief Executive Officer\n6  Richard McLaughlin MD MBA Chief Executive Officer\n7             Laura Murnyack             Interim CEO\n8                  Adam Beck Chief Executive Officer\n9                Pamela Keen Chief Executive Officer\n10              Mark Papalia           President/CEO\n                                 FACILITY_U LONGITUDE       COUNTY\n1              https://www.phhealthcare.org -79.91131   Washington\n2                 https://www.malvernbh.com -75.17005 Philadelphia\n3            https://roxboroughmemorial.com -75.20963 Philadelphia\n4                https://www.ashospital.net -80.27907   Washington\n5                 https://www.conemaugh.org -79.02513     Somerset\n6                   https://towerhealth.org -75.61213   Montgomery\n7         https://bucktailmedicalcenter.org -77.73649      Clinton\n8  https://www.selectspecialtyhospitals.com -76.88013      Dauphin\n9          https://www.childrenshomepgh.org -79.93736    Allegheny\n10    https://www.kanecommunityhospital.com -78.81705       McKean\n                                                  FACILITY_N\n1                                  Penn Highlands Mon Valley\n2                                  MALVERN BEHAVIORAL HEALTH\n3                               Roxborough Memorial Hospital\n4                                 ADVANCED SURGICAL HOSPITAL\n5                    DLP Conemaugh Meyersdale Medical Center\n6                                    Pottstown Hospital, LLC\n7                                    Bucktail medical Center\n8  SELECT SPECIALTY HOSPITAL CENTRAL PENNSYLVANIA HARRISBURG\n9                          The Children's Home of Pittsburgh\n10              University of Pittsburgh Medical Center Kane\n                           STREET   CITY_OR_BO LATITUDE   TELEPHONE_ ZIP_CODE\n1          1163 Country Club Road  Monongahela 40.18193 724-258-1000    15063\n2  1930 South Broad Street Unit 4 Philadelphia 39.92619 610-480-8919    19145\n3               5800 Ridge Avenue Philadelphia 40.02869 215-483-9900    19128\n4        100 TRICH DRIVE\\nSUITE 1   WASHINGTON 40.15655   7248840710    15301\n5              200 Hospital Drive   Meyersdale 39.80913 814-634-5911    15552\n6           1600 East High Street    Pottstown 40.24273   6103277000    19464\n7                1001 Pine Street       Renovo 41.32789 570-923-1000    17764\n8          111 South Front Street   Harrisburg 40.25841 717-724-6604    17110\n9                5324 Penn Avenue   Pittsburgh 40.46424 412-441-4884    15224\n10                4372 US Route 6         Kane 41.67188   8148378585    16735\n                   geometry\n1  POINT (-8895686 4892415)\n2  POINT (-8367892 4855223)\n3  POINT (-8372298 4870112)\n4  POINT (-8936626 4888717)\n5  POINT (-8797037 4838244)\n6  POINT (-8417104 4901278)\n7  POINT (-8653586 5060826)\n8  POINT (-8558256 4903566)\n9  POINT (-8898587 4933636)\n10 POINT (-8773874 5111954)\n```\n\n\n:::\n:::\n\n\n-   How many census tracts? – **3445 census tracts**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(census_tracts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 3445 features and 13 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -8963433 ymin: 4825308 xmax: -8314399 ymax: 5201489\nProjected CRS: WGS 84 / Pseudo-Mercator\nFirst 10 features:\n   STATEFP COUNTYFP TRACTCE              GEOIDFQ       GEOID   NAME\n1       42      001  031101 1400000US42001031101 42001031101 311.01\n2       42      013  100400 1400000US42013100400 42013100400   1004\n3       42      013  100500 1400000US42013100500 42013100500   1005\n4       42      013  100800 1400000US42013100800 42013100800   1008\n5       42      013  101900 1400000US42013101900 42013101900   1019\n6       42      011  011200 1400000US42011011200 42011011200    112\n7       42      011  000200 1400000US42011000200 42011000200      2\n8       42      011  011500 1400000US42011011500 42011011500    115\n9       42      011  000600 1400000US42011000600 42011000600      6\n10      42      011  001900 1400000US42011001900 42011001900     19\n              NAMELSAD STUSPS   NAMELSADCO   STATE_NAME LSAD   ALAND AWATER\n1  Census Tract 311.01     PA Adams County Pennsylvania   CT 3043185      0\n2    Census Tract 1004     PA Blair County Pennsylvania   CT  993724      0\n3    Census Tract 1005     PA Blair County Pennsylvania   CT 1130204      0\n4    Census Tract 1008     PA Blair County Pennsylvania   CT  996553      0\n5    Census Tract 1019     PA Blair County Pennsylvania   CT  573726      0\n6     Census Tract 112     PA Berks County Pennsylvania   CT 1539365   9308\n7       Census Tract 2     PA Berks County Pennsylvania   CT 1949529 159015\n8     Census Tract 115     PA Berks County Pennsylvania   CT 1978380  12469\n9       Census Tract 6     PA Berks County Pennsylvania   CT 1460473      0\n10     Census Tract 19     PA Berks County Pennsylvania   CT  182420      0\n                         geometry\n1  MULTIPOLYGON (((-8575060 48...\n2  MULTIPOLYGON (((-8730207 49...\n3  MULTIPOLYGON (((-8729297 49...\n4  MULTIPOLYGON (((-8728636 49...\n5  MULTIPOLYGON (((-8728378 49...\n6  MULTIPOLYGON (((-8455198 49...\n7  MULTIPOLYGON (((-8455907 49...\n8  MULTIPOLYGON (((-8460184 49...\n9  MULTIPOLYGON (((-8450851 49...\n10 MULTIPOLYGON (((-8451174 49...\n```\n\n\n:::\n:::\n\n\n-   What coordinate reference system is each dataset in? – **all datasets have\n    been projected to WGS 84 / Psuedo-Mercator**\n\n--------------------------------------------------------------------------------\n\n#### Step 2: Get Demographic Data\n\nUse `tidycensus` to download tract-level demographic data for Pennsylvania.\n\n**Required variables:** - Total population - Median household income -\nPopulation 65 years and over (you may need to sum multiple age categories)\n\n**Your Task:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load all available variables for ACS 5-year 2022\nacs_vars_2022 <- load_variables(2022, \"acs5\", cache = TRUE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Helper Variable for Summing Population Values for Elderly Population\nelderly_pop = c(\"B01001_020\", \"B01001_021\", \"B01001_022\", \"B01001_023\", \n                \"B01001_024\", \"B01001_025\", \n                \"B01001_044\", \"B01001_045\", \"B01001_046\", \n                \"B01001_047\", \"B01001_048\", \"B01001_049\")\n\n# Get tract-level demographic data from ACS\npa_data <- get_acs(\n  geography = \"tract\",\n  variables = c(\n    total_pop = \"B01003_001\",\n    median_income = \"B19013_001\",\n    elderly_pop = elderly_pop\n  ),\n  state = \"PA\",\n  year = 2022,\n  survey = \"acs5\",\n  output = \"wide\" \n)\n\n# Clean the county names to remove state name and \"County\" \npa_clean <- pa_data |> \n  separate(\n    NAME, \n    into = c(\"tract_name\", \"county_name\", \"state_name\"), \n    sep = \"; \"\n  ) |> \n  mutate(\n    tract_name = str_remove(tract_name, \"Census Tract \"),\n    county_name = str_remove(county_name, \" County\")\n  )\nhead(pa_clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 32\n  GEOID   tract_name county_name state_name total_popE total_popM median_incomeE\n  <chr>   <chr>      <chr>       <chr>           <dbl>      <dbl>          <dbl>\n1 420010… 301.01     Adams       Pennsylva…       2658         14          80231\n2 420010… 301.03     Adams       Pennsylva…       2416        329         111603\n3 420010… 301.04     Adams       Pennsylva…       3395        332          81150\n4 420010… 302        Adams       Pennsylva…       5475        464          68363\n5 420010… 303        Adams       Pennsylva…       4412        215          81577\n6 420010… 304        Adams       Pennsylva…       5462        206          88558\n# ℹ 25 more variables: median_incomeM <dbl>, elderly_pop1E <dbl>,\n#   elderly_pop1M <dbl>, elderly_pop2E <dbl>, elderly_pop2M <dbl>,\n#   elderly_pop3E <dbl>, elderly_pop3M <dbl>, elderly_pop4E <dbl>,\n#   elderly_pop4M <dbl>, elderly_pop5E <dbl>, elderly_pop5M <dbl>,\n#   elderly_pop6E <dbl>, elderly_pop6M <dbl>, elderly_pop7E <dbl>,\n#   elderly_pop7M <dbl>, elderly_pop8E <dbl>, elderly_pop8M <dbl>,\n#   elderly_pop9E <dbl>, elderly_pop9M <dbl>, elderly_pop10E <dbl>, …\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sum elderly population\npa_summary <- pa_clean |>\n  mutate(\n    elderly_popE = rowSums(across(matches(\"^elderly_pop\\\\d+E$\")), na.rm = TRUE),\n    # for MOE, ACS guidance is to combine by quadrature\n    elderly_popM = sqrt(rowSums(across(matches(\"^elderly_pop\\\\d+M$\"))^2, na.rm = \n                                  TRUE)),\n    pct_elderly = elderly_popE / total_popE\n  ) |>\n  select(GEOID, tract_name, county_name, total_popE, median_incomeE, elderly_popE, \n         elderly_popM, pct_elderly)\nhead(pa_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 8\n  GEOID       tract_name county_name total_popE median_incomeE elderly_popE\n  <chr>       <chr>      <chr>            <dbl>          <dbl>        <dbl>\n1 42001030101 301.01     Adams             2658          80231          521\n2 42001030103 301.03     Adams             2416         111603          467\n3 42001030104 301.04     Adams             3395          81150          730\n4 42001030200 302        Adams             5475          68363         1020\n5 42001030300 303        Adams             4412          81577          722\n6 42001030400 304        Adams             5462          88558         1206\n# ℹ 2 more variables: elderly_popM <dbl>, pct_elderly <dbl>\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Join to tract boundaries\ntracts_with_data <- census_tracts |> \n  left_join(pa_summary, by = \"GEOID\")\n\n# Map to confirm\nggplot(tracts_with_data) + \n  geom_sf(aes(fill = median_incomeE), linewidth = 0) +\n  scale_fill_continuous(labels = label_dollar()) + \n  labs(fill = \"Median Income\") + \n  theme_void()\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n**Questions to answer:**\n\n-   What year of ACS data are you using? – **2022 5-Year Estimates**\n\n-   How many tracts have missing income data? – **63**\n\n-   What is the median income across all PA census tracts? – **\\$70,188**\n\n\n::: {.cell}\n\n```{.r .cell-code}\npa_tract_income_qns <- pa_summary |>\n  summarize(\n    tracts_missing_income = sum(is.na(median_incomeE)),\n    tracts_median_income = median(median_incomeE, na.rm = TRUE),\n    tract_median_elderly = mean(pct_elderly, na.rm = TRUE)\n  )\npa_tract_income_qns\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  tracts_missing_income tracts_median_income tract_median_elderly\n                  <int>                <dbl>                <dbl>\n1                    63                70188                0.190\n```\n\n\n:::\n:::\n\n\n--------------------------------------------------------------------------------\n\n#### Step 3: Define Vulnerable Populations\n\nIdentify census tracts with vulnerable populations based on TWO criteria:\n\n1.  Low median household income (choose an appropriate threshold) – **\\$70,000**\n2.  Significant elderly population (choose an appropriate threshold) – **25%**;\n\n**Your Task:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on your criteria\npa_vulnerable <- pa_summary |> \n  filter(median_incomeE <= 70000 & pct_elderly >= 0.25)\npa_vulnerable\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 293 × 8\n   GEOID       tract_name county_name total_popE median_incomeE elderly_popE\n   <chr>       <chr>      <chr>            <dbl>          <dbl>        <dbl>\n 1 42001030902 309.02     Adams             4181          69855         1532\n 2 42003040400 404        Allegheny         1629          60329          705\n 3 42003100500 1005       Allegheny         2023          62411          536\n 4 42003130700 1307       Allegheny         2068          30518          537\n 5 42003270100 2701       Allegheny         2459          61481          633\n 6 42003320400 3204       Allegheny         1846          66691          465\n 7 42003416000 4160       Allegheny         1475          58654          394\n 8 42003417100 4171       Allegheny         2131          68284          536\n 9 42003420000 4200       Allegheny         1532          43333          460\n10 42003427200 4272       Allegheny         4544          56912         1163\n# ℹ 283 more rows\n# ℹ 2 more variables: elderly_popM <dbl>, pct_elderly <dbl>\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n\n-   What income threshold did you choose and why? - **\\$70,000. This threshold\n    is slightly below median income across all PA census tracts of \\$70,188**\n\n-   What elderly population threshold did you choose and why? - **25%. This\n    threshold is slightly higher than the mean percentage elderly population\n    across all PA census tracts of 19.0%**\n\n-   How many tracts meet your vulnerability criteria? - **293 tracts**\n\n-   What percentage of PA census tracts are considered vulnerable by your\n    definition? = **8.5% are considered vulnerable**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Percentage of PA census tracts considered vulnerable\n293 / 3445\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0850508\n```\n\n\n:::\n:::\n\n\n--------------------------------------------------------------------------------\n\n#### Step 4: Calculate Distance to Hospitals\n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n**Your Task:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Update Median Income Map from Step 2\nvulnerable_tracts <- tracts_with_data |>\n  filter(median_incomeE <= 70000, pct_elderly >= 0.25)   \n\n# Project to Accurate Projected CRS of NAD 83 / Pennsylvania South State Plane\npa_crs <- 32129\nvul_proj <- st_transform(vulnerable_tracts, pa_crs)\nhosp_proj   <- st_transform(hospitals, pa_crs)\n\n# Map to confirm\nggplot(vul_proj) + \n  geom_sf(aes(fill = median_incomeE), linewidth = 0) +\n  scale_fill_continuous(labels = label_dollar()) + \n  labs(fill = \"Median Income\") + \n  theme_void()\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(hosp_proj) + \n  geom_sf() + \n  theme_void()\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-13-2.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate distance from each centroid to nearest hospital, then convert to miles\ncentroids <- st_centroid(vul_proj, of_largest_polygon = TRUE)              \nnn_idx    <- st_nearest_feature(centroids, hosp_proj)         \ndist_m    <- st_distance(centroids, hosp_proj[nn_idx, ], by_element = TRUE)\n\nvul_proj$dist_nearest_hosp_mi <- set_units(dist_m, \"mi\") |> drop_units()\n\nvul_proj |>\n  st_drop_geometry() |>\n  select(GEOID, tract_name, county_name, dist_nearest_hosp_mi) |>\n  arrange(desc(dist_nearest_hosp_mi)) |>\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         GEOID tract_name county_name dist_nearest_hosp_mi\n1  42103950104    9501.04        Pike             29.11594\n2  42113960201    9602.01    Sullivan             19.85868\n3  42023960200       9602     Cameron             19.46556\n4  42043025300        253     Dauphin             19.15826\n5  42127960100       9601       Wayne             18.32885\n6  42053530200       5302      Forest             18.13084\n7  42061951100       9511  Huntingdon             17.71162\n8  42103950902    9509.02        Pike             17.52023\n9  42033330600       3306  Clearfield             17.29267\n10 42105950500       9505      Potter             17.12490\n```\n\n\n:::\n:::\n\n\n**Requirements:**\n\n-   Use an appropriate projected coordinate system for Pennsylvania\n\n-   Calculate distances in miles\n\n-   Explain why you chose your projection\n\n**Questions to answer:**\n\n-   What is the average distance to the nearest hospital for vulnerable tracts?\n    – **5.70 miles**\n\n-   What is the maximum distance? – **29.1 miles**\n\n\n::: {.cell}\n\n```{.r .cell-code}\npa_vul_tract_qns <- vul_proj |>\n  st_drop_geometry() |>\n  summarize(\n    average_distance = mean(dist_nearest_hosp_mi, na.rm = TRUE),\n    max_distance = max(dist_nearest_hosp_mi),\n  )\npa_vul_tract_qns\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  average_distance max_distance\n1         5.699299     29.11594\n```\n\n\n:::\n:::\n\n\n-   How many vulnerable tracts are more than 15 miles from the nearest hospital?\n    – **17 vulnerable tracts**\n\n\n::: {.cell}\n\n```{.r .cell-code}\npa_num_vul_qns <- vul_proj |>\n  st_drop_geometry() |>\n  filter(dist_nearest_hosp_mi > 15)\npa_num_vul_qns\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   STATEFP COUNTYFP TRACTCE              GEOIDFQ       GEOID    NAME\n1       42      023  960200 1400000US42023960200 42023960200    9602\n2       42      067  070201 1400000US42067070201 42067070201  702.01\n3       42      071  014601 1400000US42071014601 42071014601  146.01\n4       42      113  960201 1400000US42113960201 42113960201 9602.01\n5       42      061  951100 1400000US42061951100 42061951100    9511\n6       42      043  025300 1400000US42043025300 42043025300     253\n7       42      127  960100 1400000US42127960100 42127960100    9601\n8       42      015  950900 1400000US42015950900 42015950900    9509\n9       42      039  110400 1400000US42039110400 42039110400    1104\n10      42      103  950104 1400000US42103950104 42103950104 9501.04\n11      42      103  950902 1400000US42103950902 42103950902 9509.02\n12      42      111  021903 1400000US42111021903 42111021903  219.03\n13      42      105  950500 1400000US42105950500 42105950500    9505\n14      42      113  960202 1400000US42113960202 42113960202 9602.02\n15      42      033  330600 1400000US42033330600 42033330600    3306\n16      42      103  950304 1400000US42103950304 42103950304 9503.04\n17      42      053  530200 1400000US42053530200 42053530200    5302\n               NAMELSAD STUSPS        NAMELSADCO   STATE_NAME LSAD      ALAND\n1     Census Tract 9602     PA    Cameron County Pennsylvania   CT 1024403718\n2   Census Tract 702.01     PA    Juniata County Pennsylvania   CT  269992268\n3   Census Tract 146.01     PA  Lancaster County Pennsylvania   CT   59917674\n4  Census Tract 9602.01     PA   Sullivan County Pennsylvania   CT  390602391\n5     Census Tract 9511     PA Huntingdon County Pennsylvania   CT  205881326\n6      Census Tract 253     PA    Dauphin County Pennsylvania   CT   67051563\n7     Census Tract 9601     PA      Wayne County Pennsylvania   CT  228985189\n8     Census Tract 9509     PA   Bradford County Pennsylvania   CT  227326822\n9     Census Tract 1104     PA   Crawford County Pennsylvania   CT  124797191\n10 Census Tract 9501.04     PA       Pike County Pennsylvania   CT   74698417\n11 Census Tract 9509.02     PA       Pike County Pennsylvania   CT  221424684\n12  Census Tract 219.03     PA   Somerset County Pennsylvania   CT  161766951\n13    Census Tract 9505     PA     Potter County Pennsylvania   CT  632071788\n14 Census Tract 9602.02     PA   Sullivan County Pennsylvania   CT  329132436\n15    Census Tract 3306     PA Clearfield County Pennsylvania   CT  149295977\n16 Census Tract 9503.04     PA       Pike County Pennsylvania   CT   31048279\n17    Census Tract 5302     PA     Forest County Pennsylvania   CT  572305586\n     AWATER tract_name county_name total_popE median_incomeE elderly_popE\n1   5543936       9602     Cameron       2548          56172          841\n2      1972     702.01     Juniata       1782          48958          492\n3    213842     146.01   Lancaster       3932          65610          994\n4    935042    9602.01    Sullivan       1700          63317          524\n5      9786       9511  Huntingdon       1966          67672          528\n6  13834393        253     Dauphin       4018          54698         1066\n7   5417146       9601       Wayne       1137          58393          367\n8   7145637       9509    Bradford       5466          51875         1545\n9  17659987       1104    Crawford       2536          51078          645\n10  1696431    9501.04        Pike       2628          57394          890\n11  8141470    9509.02        Pike       1244          61534          440\n12   327847     219.03    Somerset       1266          62981          342\n13   236632       9505      Potter       1948          54779          559\n14  1725112    9602.02    Sullivan        918          51719          282\n15  1068529       3306  Clearfield       3343          49659          987\n16   567416    9503.04        Pike        696          57475          346\n17  7902354       5302      Forest       2701          47132          802\n   elderly_popM pct_elderly dist_nearest_hosp_mi\n1      87.36704   0.3300628             19.46556\n2      87.61278   0.2760943             15.90783\n3     244.86527   0.2527976             15.02917\n4      62.96030   0.3082353             19.85868\n5     104.65180   0.2685656             17.71162\n6     190.80356   0.2653061             19.15826\n7      61.43289   0.3227792             18.32885\n8     188.92856   0.2826564             16.65873\n9      83.42661   0.2543375             16.25278\n10    160.91302   0.3386606             29.11594\n11    142.05985   0.3536977             17.52023\n12     61.31884   0.2701422             15.24454\n13     56.78908   0.2869610             17.12490\n14     43.98863   0.3071895             16.90745\n15    162.93557   0.2952438             17.29267\n16    100.53358   0.4971264             15.75241\n17     86.08136   0.2969271             18.13084\n```\n\n\n:::\n:::\n\n\n--------------------------------------------------------------------------------\n\n#### Step 5: Identify Underserved Areas\n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the\nnearest hospital.\n\n**Questions to answer:**\n\n-   How many tracts are underserved? – **17 tracts (same as last question of\n    Step 4)**\n\n-   What percentage of vulnerable tracts are underserved? – **5.8% of vulnerable\n    tracts are underserved**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n17 / 293\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.05802048\n```\n\n\n:::\n:::\n\n\n-   Does this surprise you? Why or why not? – **This low percentage does not\n    surprise me, given that Pennsylvania is home to the hospital system of Penn\n    Medicine and the Children's Hospital of Philadelphia (CHOP).**\n\n--------------------------------------------------------------------------------\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about\nvulnerable populations and hospital access.\n\n**Your Task:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Normalize the county layer (create county_geoid + county_name)\npa_counties_norm <- pa_counties |> \n  mutate(\n    county_geoid = paste0(\"42\", str_pad(as.character(FIPS_COUNT), 3, pad = \"0\")),\n    county_name  = COUNTY_NAM\n  ) |> \n  st_transform(32129) |>                     # PA South State Plane (meters)\n  select(county_geoid, county_name, geometry)\n\n# Define underserved threshold\nunderserved_threshold_mi <- 15\n\n# Spatial join tracts → counties and aggregate\ncounty_summary <- pa_counties_norm |> \n  st_join(\n    vul_proj |> \n      mutate(underserved = dist_nearest_hosp_mi > underserved_threshold_mi) |> \n      select(tr_geoid = GEOID,\n             dist_nearest_hosp_mi,\n             total_popE,\n             elderly_popE,\n             underserved),\n    join = st_intersects,\n    left = TRUE                                  # keep all 67 counties\n  ) %>%\n  st_drop_geometry() |> \n  group_by(county_geoid, county_name) |> \n  summarise(\n    n_vulnerable_tracts        = sum(!is.na(tr_geoid)),\n    n_underserved_tracts       = sum(underserved %in% TRUE, na.rm = TRUE),\n    pct_vuln_underserved       = 100 * n_underserved_tracts / n_vulnerable_tracts,\n    avg_dist_nearest_hosp_mi   = mean(dist_nearest_hosp_mi, na.rm = TRUE),\n    total_vulnerable_residents = sum(replace_na(total_popE, 0), na.rm = TRUE),\n  ) |> \nungroup() |> \narrange(desc(pct_vuln_underserved))\n\ncounty_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 67 × 7\n   county_geoid county_name n_vulnerable_tracts n_underserved_tracts\n   <chr>        <chr>                     <int>                <int>\n 1 42043        DAUPHIN                       1                    1\n 2 42099        PERRY                         2                    2\n 3 42015        BRADFORD                      3                    2\n 4 42035        CLINTON                       3                    2\n 5 42113        SULLIVAN                      3                    2\n 6 42023        CAMERON                       2                    1\n 7 42057        FULTON                        2                    1\n 8 42067        JUNIATA                       4                    2\n 9 42033        CLEARFIELD                    5                    2\n10 42055        FRANKLIN                      5                    2\n# ℹ 57 more rows\n# ℹ 3 more variables: pct_vuln_underserved <dbl>,\n#   avg_dist_nearest_hosp_mi <dbl>, total_vulnerable_residents <dbl>\n```\n\n\n:::\n:::\n\n\n**Required county-level statistics:** - Number of vulnerable tracts - Number of\nunderserved tracts\\\n- Percentage of vulnerable tracts that are underserved - Average distance to\nnearest hospital for vulnerable tracts - Total vulnerable population\n\n**Questions to answer:**\n\n-   Which 5 counties have the highest percentage of underserved vulnerable\n    tracts? – **Dauphin, Perry, Bradford, Clinton, Sullivan**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nslice(county_summary, 1:5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 7\n  county_geoid county_name n_vulnerable_tracts n_underserved_tracts\n  <chr>        <chr>                     <int>                <int>\n1 42043        DAUPHIN                       1                    1\n2 42099        PERRY                         2                    2\n3 42015        BRADFORD                      3                    2\n4 42035        CLINTON                       3                    2\n5 42113        SULLIVAN                      3                    2\n# ℹ 3 more variables: pct_vuln_underserved <dbl>,\n#   avg_dist_nearest_hosp_mi <dbl>, total_vulnerable_residents <dbl>\n```\n\n\n:::\n:::\n\n\n-   Which counties have the most vulnerable people living far from hospitals?\n    **– Pike, Bradford, Forest, Sullivan, Perry, Fulton, and Dauphin**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_summary |> \n  filter(avg_dist_nearest_hosp_mi > 15) |> \n  arrange(desc(total_vulnerable_residents))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 7\n  county_geoid county_name n_vulnerable_tracts n_underserved_tracts\n  <chr>        <chr>                     <int>                <int>\n1 42103        PIKE                          8                    3\n2 42015        BRADFORD                      3                    2\n3 42053        FOREST                        3                    1\n4 42113        SULLIVAN                      3                    2\n5 42099        PERRY                         2                    2\n6 42057        FULTON                        2                    1\n7 42043        DAUPHIN                       1                    1\n# ℹ 3 more variables: pct_vuln_underserved <dbl>,\n#   avg_dist_nearest_hosp_mi <dbl>, total_vulnerable_residents <dbl>\n```\n\n\n:::\n:::\n\n\n-   Are there any patterns in where underserved counties are located?\n\n--------------------------------------------------------------------------------\n\n#### Step 7: Create Summary Table\n\nCreate a professional table showing the top 10 priority counties for healthcare\ninvestment.\n\n**Your Task:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\npriority_counties <- county_summary |> \n  arrange(desc(avg_dist_nearest_hosp_mi), desc(total_vulnerable_residents)) |> \n  select(county_name, total_vulnerable_residents, n_vulnerable_tracts, \n         n_underserved_tracts, avg_dist_nearest_hosp_mi) |> \n  slice(1:10)\n\nkable(priority_counties,\n      col.names = c(\"County\", \"Vulnerable Residents\", \"Vulnerable Tracts\", \n                    \"Underserved Tracts\", \"Avg Distance to Nearest Hospital\"),\n      caption = \"Top 10 Priority Counties in PA for Healthcare Investment\",\n      format.args = list(big.mark = \",\"))\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 10 Priority Counties in PA for Healthcare Investment\n\n|County   | Vulnerable Residents| Vulnerable Tracts| Underserved Tracts| Avg Distance to Nearest Hospital|\n|:--------|--------------------:|-----------------:|------------------:|--------------------------------:|\n|DAUPHIN  |                4,018|                 1|                  1|                         19.15826|\n|PERRY    |                5,800|                 2|                  2|                         17.53304|\n|SULLIVAN |                6,079|                 3|                  2|                         16.30149|\n|BRADFORD |                9,936|                 3|                  2|                         16.18085|\n|FULTON   |                4,067|                 2|                  1|                         15.95926|\n|PIKE     |               14,125|                 8|                  3|                         15.64696|\n|FOREST   |                7,335|                 3|                  1|                         15.04744|\n|COLUMBIA |                7,645|                 3|                  1|                         14.13191|\n|CLINTON  |                7,672|                 3|                  2|                         13.84024|\n|CLARION  |               11,616|                 4|                  1|                         13.04375|\n\n\n:::\n:::\n\n\n**Requirements:**\n\n-   Use `knitr::kable()` or similar for formatting\n\n-   Include descriptive column names\n\n-   Format numbers appropriately (commas for population, percentages, etc.)\n\n-   Add an informative caption\n\n-   Sort by priority (you decide the metric)\n\n--------------------------------------------------------------------------------\n\n## Part 2: Comprehensive Visualization\n\nUsing the skills from Week 3 (Data Visualization), create publication-quality\nmaps and charts.\n\n### Map 1: County-Level Choropleth\n\nCreate a choropleth map showing healthcare access challenges at the county\nlevel.\n\n**Your Task:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(scales)\nlibrary(RColorBrewer)\n\n# Spatial Joins and Projections\ncounty_summary_sf <- pa_counties_norm %>%\n  left_join(county_summary, by = \"county_geoid\")\nhosp_pts <- hospitals %>% st_transform(st_crs(county_summary_sf))\n\n# Create county-level access map\nggplot(county_summary_sf) +\n  geom_sf(aes(fill = pct_vuln_underserved), color = \"white\", linewidth = 0.25) +\n  geom_sf(data = hosp_pts, size = 0.9, alpha = 0.8) +\n  scale_fill_distiller(\n    name = \"% of vulnerable tracts\\n> 15 miles from a hospital\",\n    palette = \"Reds\",       \n    direction = 1,          # light (low) -> dark (high)\n    na.value = \"grey90\",\n    limits = c(0, 100),\n    breaks = c(0, 25, 50, 75, 100),\n    labels = label_percent(accuracy = 1, scale = 1),\n    guide = guide_colorbar(barheight = unit(80, \"pt\"))\n  ) +\n  labs(\n    title = \"Healthcare Access Challenges by County — Pennsylvania\",\n    subtitle = \"Percentage of vulnerable tracts that are underserved (threshold = 15 miles)\",\n    caption  = \"Notes: Grey counties have no vulnerable tracts. Distances computed in PA South State Plane\"\n  ) +\n  theme_void() +\n  theme(legend.position = \"right\")\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n**Requirements:** - Fill counties by percentage of vulnerable tracts that are\nunderserved - Include hospital locations as points - Use an appropriate color\nscheme - Include clear title, subtitle, and caption - Use `theme_void()` or\nsimilar clean theme - Add a legend with formatted labels\n\n--------------------------------------------------------------------------------\n\n### Map 2: Detailed Vulnerability Map\n\nCreate a map highlighting underserved vulnerable tracts.\n\n**Your Task:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create detailed tract-level map\nunderserved_threshold_mi <- 15\nvul_status <- vul_proj |> \n  mutate(\n    status = if_else(dist_nearest_hosp_mi > underserved_threshold_mi,\n                     \"Underserved\", \"Vulnerable\")\n  )\n\n# 2) Plot\nggplot() +\n  # Base: county boundaries for context (low visual weight)\n  geom_sf(data = pa_counties_norm, fill = NA, color = \"grey60\", linewidth = 0.3) +\n\n  # Other vulnerable tracts (de-emphasized)\n  geom_sf(data = subset(vul_status, status == \"Vulnerable\"),\n          aes(fill = status), color = NA, alpha = 0.35) +\n\n  # Underserved vulnerable tracts (primary focus)\n  geom_sf(data = subset(vul_status, status == \"Underserved\"),\n          aes(fill = status), color = \"#7f0000\", linewidth = 0.2, alpha = 0.9) +\n\n  # Hospitals (symbols on top for maximum legibility)\n  geom_sf(data = hosp_pts, aes(shape = \"Hospital\"),\n          size = 1.2, color = \"black\", fill = \"white\", stroke = 0.4) +\n\n  # Manual scales to control contrast & legend\n  scale_fill_manual(\n    name   = NULL,\n    values = c(\"Underserved\" = \"#cb181d\",  # strong red\n               \"Vulnerable\"  = \"grey80\")\n  ) +\n  scale_shape_manual(\n    name   = NULL,\n    values = c(\"Hospital\" = 21)  # filled circle w/ border\n  ) +\n  guides(\n    fill  = guide_legend(order = 1, override.aes = list(alpha = c(0.9, 0.35))),\n    shape = guide_legend(order = 2, override.aes = list(size = 3))\n  ) +\n\n  labs(\n    title    = \"Underserved Census Tracts and Hospital Locations — Pennsylvania\",\n    subtitle = \"Red tracts: vulnerable and > 15 miles from the nearest hospital\",\n    caption  = \"Distances computed in EPSG:32129 (PA South State Plane)\"\n  ) +\n  theme_void(base_size = 12) +\n  theme(\n    legend.position = \"right\",\n  ) +\n  coord_sf(datum = NA)\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n**Requirements:** - Show underserved vulnerable tracts in a contrasting color -\nInclude county boundaries for context - Show hospital locations - Use\nappropriate visual hierarchy (what should stand out?) - Include informative\ntitle and subtitle\n\n--------------------------------------------------------------------------------\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for\nvulnerable populations.\n\n**Your Task:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create distribution visualization\n\nvul_regions <- vul_proj |> \n  mutate(underserved = dist_nearest_hosp_mi > underserved_threshold_mi)\n\n# Compute tract centroids in lon/lat just for region assignment\nvul_ll <- st_transform(vul_regions, 4326)\nctr    <- st_centroid(vul_ll)\nlon    <- st_coordinates(ctr)[,1]\nq      <- quantile(lon, probs = c(1/3, 2/3), na.rm = TRUE)\n\nvul_regions <- vul_regions |> \n  mutate(region3 = case_when(\n    lon <= q[1] ~ \"West\",\n    lon >  q[2] ~ \"East\",\n    TRUE        ~ \"Central\"\n  )) %>%\n  mutate(region3 = factor(region3, levels = c(\"West\",\"Central\",\"East\")))\n\n# 1) Histogram of distances (with underserved threshold)\np_hist <- ggplot(vul_regions, aes(x = dist_nearest_hosp_mi)) +\n  geom_histogram(binwidth = 2, boundary = 0, closed = \"left\",\n                 fill = \"#9ecae1\", color = \"white\") +\n  geom_vline(xintercept = underserved_threshold_mi, linetype = \"dashed\") +\n  labs(\n    title   = \"Distribution of Distances to the Nearest Hospital (Vulnerable Tracts)\",\n    x       = \"Distance to nearest hospital (miles)\",\n    y       = \"Number of tracts\",\n    caption = \"Dashed line marks the underserved threshold (15 miles). Look for right-skew and the share beyond the threshold.\"\n  ) +\n  theme_minimal(base_size = 12)\n\n# 2) Box plot by regions (West/Central/East)\np_box <- ggplot(vul_regions, aes(x = region3, y = dist_nearest_hosp_mi, fill = region3)) +\n  geom_boxplot(outlier.alpha = 0.3) +\n  geom_hline(yintercept = underserved_threshold_mi, linetype = \"dashed\") +\n  scale_fill_brewer(palette = \"Set2\", guide = \"none\") +\n  labs(\n    title    = \"Distance to Hospital by Region (Vulnerable Tracts)\",\n    subtitle = \"Regions defined by longitude terciles (West, Central, East)\",\n    x        = NULL,\n    y        = \"Distance to nearest hospital (miles)\",\n    caption  = \"Regions with higher medians indicate broader access challenges.\"\n  ) +\n  theme_minimal(base_size = 12)\n\n# 3) Bar chart: underserved tracts by county (Top 15 for readability)\nbar_df <- county_summary %>%\n  select(county_name, n_underserved_tracts) %>%\n  arrange(desc(n_underserved_tracts)) %>%\n  slice_head(n = 15)\n\np_bar <- ggplot(bar_df,\n                aes(x = reorder(county_name, n_underserved_tracts),\n                    y = n_underserved_tracts)) +\n  geom_col(fill = \"#cb181d\") +\n  coord_flip() +\n  labs(\n    title   = \"Underserved Vulnerable Tracts by County (Top 15)\",\n    x       = NULL,\n    y       = \"Underserved vulnerable tracts (count)\",\n    caption = \"Highlights where the count of tracts beyond 15 miles is most concentrated.\"\n  ) +\n  theme_minimal(base_size = 12)\n\n# 4) Scatter: distance vs. vulnerable population size (per tract)\np_scatter <- ggplot(vul_regions,\n                    aes(x = dist_nearest_hosp_mi,\n                        y = total_popE,\n                        color = underserved)) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(method = \"loess\", se = FALSE,\n              linetype = \"dashed\", color = \"black\", linewidth = 0.8) +\n  scale_color_manual(\n    values = c(`TRUE` = \"#cb181d\", `FALSE` = \"grey60\"),\n    name   = \"Underserved?\",\n    labels = c(\"No (≤ 15 mi)\", \"Yes (> 15 mi)\")\n  ) +\n  scale_y_continuous(labels = comma) +\n  labs(\n    title   = \"Distance vs. Vulnerable Population Size (Tracts)\",\n    x       = \"Distance to nearest hospital (miles)\",\n    y       = \"Vulnerable population (tract total)\",\n    caption = \"Dashed curve shows the local trend\"\n  ) +\n  theme_minimal(base_size = 12)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_hist\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n\n```{.r .cell-code}\np_box\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-25-2.png){width=672}\n:::\n\n```{.r .cell-code}\np_bar\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-25-3.png){width=672}\n:::\n\n```{.r .cell-code}\np_scatter\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-25-4.png){width=672}\n:::\n:::\n\n\n**Suggested chart types:** - Histogram or density plot of distances - Box plot\ncomparing distances across regions - Bar chart of underserved tracts by county -\nScatter plot of distance vs. vulnerable population size\n\n**Requirements:** - Clear axes labels with units - Appropriate title -\nProfessional formatting - Brief interpretation (1-2 sentences as a caption or in\ntext)\n\n--------------------------------------------------------------------------------\n\n## Part 3: Bring Your Own Data Analysis\n\nChoose your own additional spatial dataset and conduct a supplementary analysis.\n\n### Challenge Options\n\nChoose ONE of the following challenge exercises, or propose your own research\nquestion using OpenDataPhilly data (https://opendataphilly.org/datasets/).\n\n**Note these are just loose suggestions to spark ideas - follow or make your own\nas the data permits and as your ideas evolve. This analysis should include\nbringing in your own dataset, ensuring the projection/CRS of your layers align\nand are appropriate for the analysis (not lat/long or geodetic coordinate\nsystems). The analysis portion should include some combination of spatial and\nattribute operations to answer a relatively straightforward question**\n\n--------------------------------------------------------------------------------\n\n#### Education & Youth Services\n\n**Option A: Educational Desert Analysis**\n\n-   **Data:** Schools, Libraries, Recreation Centers, Census tracts (child\n    population)\n\n-   **Question:** \"Which neighborhoods lack adequate educational infrastructure\n    for children?\"\n\n-   **Operations:** Buffer schools/libraries (0.5 mile walking distance),\n    identify coverage gaps, overlay with child population density\n\n-   **Policy relevance:** School district planning, library placement,\n    after-school program siting\n\n**Option B: School Safety Zones**\n\n-   **Data:** Schools, Crime Incidents, Bike Network\n\n-   **Question:** \"Are school zones safe for walking/biking, or are they crime\n    hotspots?\"\n\n-   **Operations:** Buffer schools (1000ft safety zone), spatial join with crime\n    incidents, assess bike infrastructure coverage\n\n-   **Policy relevance:** Safe Routes to School programs, crossing guard\n    placement\n\n--------------------------------------------------------------------------------\n\n#### Environmental Justice\n\n**Option C: Green Space Equity**\n\n-   **Data:** Parks, Street Trees, Census tracts (race/income demographics)\n-   **Question:** \"Do low-income and minority neighborhoods have equitable\n    access to green space?\"\n-   **Operations:** Buffer parks (10-minute walk = 0.5 mile), calculate tree\n    canopy or park acreage per capita, compare by demographics\n-   **Policy relevance:** Climate resilience, environmental justice, urban\n    forestry investment\n\n--------------------------------------------------------------------------------\n\n#### Public Safety & Justice\n\n**Option D: Crime & Community Resources**\n\n-   **Data:** Crime Incidents, Recreation Centers, Libraries, Street Lights\n\n-   **Question:** \"Are high-crime areas underserved by community resources?\"\n\n-   **Operations:** Aggregate crime counts to census tracts or neighborhoods,\n    count community resources per area, spatial correlation analysis\n\n-   **Policy relevance:** Community investment, violence prevention strategies\n\n--------------------------------------------------------------------------------\n\n#### Infrastructure & Services\n\n**Option E: Polling Place Accessibility**\n\n-   **Data:** Polling Places, SEPTA stops, Census tracts (elderly population,\n    disability rates)\n\n-   **Question:** \"Are polling places accessible for elderly and disabled\n    voters?\"\n\n-   **Operations:** Buffer polling places and transit stops, identify vulnerable\n    populations, find areas lacking access\n\n-   **Policy relevance:** Voting rights, election infrastructure, ADA compliance\n\n--------------------------------------------------------------------------------\n\n#### Health & Wellness\n\n**Option F: Recreation & Population Health**\n\n-   **Data:** Recreation Centers, Playgrounds, Parks, Census tracts\n    (demographics)\n\n-   **Question:** \"Is lack of recreation access associated with vulnerable\n    populations?\"\n\n-   **Operations:** Calculate recreation facilities per capita by neighborhood,\n    buffer facilities for walking access, overlay with demographic indicators\n\n-   **Policy relevance:** Public health investment, recreation programming,\n    obesity prevention\n\n--------------------------------------------------------------------------------\n\n#### Emergency Services\n\n**Option G: EMS Response Coverage**\n\n-   **Data:** Fire Stations, EMS stations, Population density, High-rise\n    buildings\n\n-   **Question:** \"Are population-dense areas adequately covered by emergency\n    services?\"\n\n-   **Operations:** Create service area buffers (5-minute drive = \\~2 miles),\n    assess population coverage, identify gaps in high-density areas\n\n-   **Policy relevance:** Emergency preparedness, station siting decisions\n\n--------------------------------------------------------------------------------\n\n#### Arts & Culture\n\n**Option H: Cultural Asset Distribution**\n\n-   **Data:** Public Art, Museums, Historic sites/markers, Neighborhoods\n\n-   **Question:** \"Do all neighborhoods have equitable access to cultural\n    amenities?\"\n\n-   **Operations:** Count cultural assets per neighborhood, normalize by\n    population, compare distribution across demographic groups\n\n-   **Policy relevance:** Cultural equity, tourism, quality of life,\n    neighborhood identity\n\n--------------------------------------------------------------------------------\n\n### Data Sources\n\n**OpenDataPhilly:** https://opendataphilly.org/datasets/ - Most datasets\navailable as GeoJSON, Shapefile, or CSV with coordinates - Always check the\nMetadata for a data dictionary of the fields.\n\n**Additional Sources:**\n\n-   **Pennsylvania Open Data:** https://data.pa.gov/\n\n-   **Census Bureau (via tidycensus):** Demographics, economic indicators,\n    commute patterns\n\n-   **TIGER/Line (via tigris):** Geographic boundaries\n\n### Recommended Starting Points\n\n**If you're feeling confident:** Choose an advanced challenge with multiple data\nlayers. **If you are a beginner, choose something more manageable that helps you\nunderstand the basics**\n\n**If you have a different idea:** Propose your own question! Just make sure:\n\n-   You can access the spatial data\n\n-   You can perform at least 2 spatial operations\n\n### Your Analysis\n\n**My Chosen Question: School Access and School Choice in City of Philadelphia**\n\n-   **Data**: Schools, Census Tracts (race/income demographics)\n    -   School Parcels: <https://opendataphilly.org/datasets/schools-parcels/> –\n        parcel location of schools in the City of Philadelphia with attribute\n        information for address, grade level, type, and status\n    -   Schools: <https://opendataphilly.org/datasets/schools/> – points\n        identifying public schools, charter schools, many private schools,\n        school annexes, and athletic fields and facilities\n-   **Question:** \"Is lack of school access associated with vulnerable\n    populations?\"\n-   **Operations:**\n    -   Clean datasets\n    -   Distance to nearest school\n    -   Buffer schools (10-minute walk = 0.5 mile)\n    -   Compare types and enrollment of schools by demographics\n\n**Your Task:**\n\n1.  **Find and load additional data**\n    -   Document your data source\n    -   Check and standardize the CRS\n    -   Provide basic summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load your additional dataset\ngetwd()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"C:/Users/chewj/Documents/MUSA/Github/portfolio-setup-jedchewjm/labs/lab_2\"\n```\n\n\n:::\n\n```{.r .cell-code}\nphl_schools <- st_read(\"data/parcels.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Schools_Parcels' from data source \n  `C:\\Users\\chewj\\Documents\\MUSA\\Github\\portfolio-setup-jedchewjm\\labs\\lab_2\\data\\Parcels.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 495 features and 17 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -75.2683 ymin: 39.90632 xmax: -74.96983 ymax: 40.13029\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nphl_school_points <- st_read(\"data/points.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Schools' from data source \n  `C:\\Users\\chewj\\Documents\\MUSA\\Github\\portfolio-setup-jedchewjm\\labs\\lab_2\\data\\Points.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 495 features and 14 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -75.2665 ymin: 39.90781 xmax: -74.97057 ymax: 40.12974\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Standardize CRS\nphl_schools <- st_transform(phl_schools, st_crs(pa_counties))\nphl_school_points <- st_transform(phl_school_points, st_crs(pa_counties))\n\nggplot(phl_schools) +\n  geom_sf() +\n  labs(title = \"PHL School Parcels\") +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(phl_school_points) +\n  geom_sf() +\n  labs(title = \"PHL School Points\") +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-27-2.png){width=672}\n:::\n:::\n\n\n**Questions to answer:**\n\n-   What dataset did you choose and why?\n\n    -   School locations to answer my research question on school access\n\n-   What is the data source and date?\n\n    -   Data Source: Open Data Philly\n\n    -   Date of School Parcels – last updated 02/02/2024 (from metadata)\n\n    -   Data of School Points – last updated 02/02/2024 (from metadata)\n\n-   How many features does it contain?\n\n    -   School Parcels – 17 features\n\n    -   School Points – 14 features\n\n-   What CRS is it in? Did you need to transform it? – WGS 84\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Helper Variables for Summing Population Values for Children aged 5-19\nchild_pop = c(\"B01001_004\", \"B01001_005\", \"B01001_006\", \"B01001_007\", \n                \"B01001_028\", \"B01001_029\", \"B01001_030\", \"B01001_031\")\n\n# Get tract-level demographic data from 2022 ACS 5-Yr Estimates for Philadelphia\nphl_data <- get_acs(\n  geography = \"tract\",\n  variables = c(\n    total_pop = \"B01003_001\",\n    child_pop = child_pop,\n    median_income = \"B19013_001\",\n    poverty = \"B17001_001\",\n    White     = \"B03002_003\",\n    Black     = \"B03002_004\",\n    Hispanic  = \"B03002_012\"\n  ),\n  state = \"PA\",\n  county = \"Philadelphia\",\n  year = 2022,\n  survey = \"acs5\",\n  output = \"wide\",\n  geometry = TRUE\n)\n\n# Clean the county names to remove state name and \"County\"\nphl_clean <- phl_data |> \n  separate(\n    NAME, \n    into = c(\"tract_name\", \"county_name\", \"state_name\"), \n    sep = \"; \"\n  ) |> \n  mutate(\n    tract_name = str_remove(tract_name, \"Census Tract \"),\n    county_name = str_remove(county_name, \" County\")\n  ) \nphl_clean\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Summarize Raw Data\nphl_summary <- phl_clean |>\n  mutate(\n    child_popE = rowSums(across(matches(\"^child_pop\\\\d+E$\")), na.rm = TRUE),\n    child_popM = sqrt(rowSums(across(matches(\"^child_pop\\\\d+M$\"))^2, na.rm = \n                                  TRUE)),\n    pct_child = round((child_popE/total_popE) * 100, 2),\n    pct_poverty = round((povertyE/total_popE) * 100, 2),\n    pct_white = round((WhiteE/total_popE) * 100, 2),\n    pct_black = round((BlackE/total_popE) * 100, 2),\n    pct_hispanic = round((HispanicE/total_popE) * 100, 2)\n  ) |>\n  select(GEOID, tract_name, median_incomeE, median_incomeM, total_popE, total_popM,\n         child_popE, child_popM, pct_child, pct_poverty, \n         pct_white, pct_black, pct_hispanic)\nhead(phl_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 13 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -75.24686 ymin: 39.91545 xmax: -75.15233 ymax: 39.94983\nGeodetic CRS:  NAD83\n        GEOID tract_name median_incomeE median_incomeM total_popE total_popM\n1 42101001500         15         110859          24975       3251        677\n2 42101001800         18         114063          30714       3300        369\n3 42101002802      28.02          78871          20396       5720        796\n4 42101004001      40.01          61583          22293       4029        437\n5 42101006300         63          32347           4840       4415        853\n6 42101007700         77          48581          13812       1815        210\n  child_popE child_popM pct_child pct_poverty pct_white pct_black pct_hispanic\n1        478   172.0785     14.70       99.63     66.29     18.39         4.77\n2        271   102.5378      8.21      100.00     73.27     10.52         3.88\n3        408   160.7420      7.13       99.83     60.70      3.11        13.27\n4        420   176.4171     10.42      100.00     71.93      3.47         9.61\n5        948   289.8327     21.47       99.89      4.12     81.36         7.38\n6        519   123.4220     28.60       65.18     53.66     20.06         5.34\n                        geometry\n1 MULTIPOLYGON (((-75.16558 3...\n2 MULTIPOLYGON (((-75.1662 39...\n3 MULTIPOLYGON (((-75.16735 3...\n4 MULTIPOLYGON (((-75.17002 3...\n5 MULTIPOLYGON (((-75.24686 3...\n6 MULTIPOLYGON (((-75.21292 3...\n```\n\n\n:::\n\n```{.r .cell-code}\n# Map to confirm\nphl_summary <- st_transform(phl_summary, st_crs(pa_counties))\n\nggplot(phl_summary) + \n  geom_sf(aes(fill = median_incomeE), linewidth = 0) +\n  scale_fill_continuous(labels = label_dollar()) + \n  labs(\n    title = \"PHL Census Tracts\",\n    fill = \"Median Income\") + \n  theme_void()\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\nNote: Philadelphia has 408 census tracts, but as the map above visualizes, some\nof these census tracts have missing/incomplete data. Hence, the next part of\nthis analysis will only use the 383 census tracts that do not have missing/NaN\nvalues\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphl_summary_clean <- phl_summary |>\n  # Drop rows with NA/NaN in any estimate column (keeps rows even if MOE is NA)\n  filter(!if_any(ends_with(\"E\"), ~ is.na(.) | is.nan(.)))\n\nggplot(phl_summary_clean) + \n  geom_sf(aes(fill = median_incomeE), linewidth = 0) +\n  scale_fill_continuous(labels = label_dollar()) + \n  labs(\n    title = \"PHL Census Tracts (Cleaned)\",\n    fill = \"Median Income\") + \n  theme_void()\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n--------------------------------------------------------------------------------\n\n2.  **Pose a research question**\n\nWrite a clear research statement that your analysis will answer.\n\n**My Research Question: Is lack of school access associated with vulnerable\npopulations?**\n\n**Examples:**\n\n-   \"Do vulnerable tracts have adequate public transit access to hospitals?\"\n\n-   Are EMS stations appropriately located near vulnerable populations?\"\n\n-   \"Do areas with low vehicle access have worse hospital access?\"\n\n--------------------------------------------------------------------------------\n\n3.  **Conduct spatial analysis**\n\nUse at least TWO spatial operations to answer your research question.\n\n**Required operations (choose 2+):**\n\n-   Buffers / Intersections / Unions / Distance Calculations\n\n-   Spatial joins\n\n-   Spatial filtering with predicates\n\n-   Point-in-polygon aggregation\n\n**Your Task:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate the Distance from each Census tract to the nearest School\ncentroids <- st_centroid(phl_summary_clean, of_largest_polygon = TRUE)            \nnn_idx    <- st_nearest_feature(centroids, phl_school_points)         \ndist_m    <- st_distance(centroids, phl_school_points[nn_idx, ], by_element = TRUE)\n\nphl_summary_clean$dist_sch_mi <- set_units(dist_m, \"mi\") |> drop_units()\n\nphl_summary_clean |>\n  st_drop_geometry() |>\n  select(GEOID, tract_name, dist_sch_mi, pct_child, pct_poverty) |>\n  arrange(desc(dist_sch_mi)) |>\n  head(20)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         GEOID tract_name dist_sch_mi pct_child pct_poverty\n1  42101005400         54   1.8638611     25.82      100.00\n2  42101034600        346   1.1450621     13.89      100.00\n3  42101036100        361   0.9349944     15.79      100.00\n4  42101034802     348.02   0.8728954     22.99      100.00\n5  42101035100        351   0.8714327      6.83       96.73\n6  42101035702     357.02   0.8627104     14.45      100.00\n7  42101005600         56   0.8353058     10.28      100.00\n8  42101033300        333   0.8318995     10.67       85.23\n9  42101012203     122.03   0.7763958      5.96      100.00\n10 42101036502     365.02   0.7215613     20.96      100.00\n11 42101033900        339   0.7099034     20.58      100.00\n12 42101980100       9801   0.6841426     17.59      100.00\n13 42101023500        235   0.6826007      9.16      100.00\n14 42101034803     348.03   0.6735394     11.88      100.00\n15 42101002000         20   0.6723388      3.80       99.61\n16 42101030700        307   0.6706962     13.22      100.00\n17 42101035800        358   0.6658125     18.47       99.25\n18 42101021800        218   0.6525663      7.46      100.00\n19 42101036301     363.01   0.6414513     18.12       99.68\n20 42101012000        120   0.6355741     23.37       73.03\n```\n\n\n:::\n:::\n\n\nNote: From this initial exploration, there is no clear linear relationship\nbetween the distance to the nearest school and the poverty percentage of a\ncensus tract. Instead, it might be useful to first identify underserved tracts\nthat are more than 0.5 miles (i.e. a 10-minute walking distance) from the\nnearest school\n\n**Identify Underserved Tracts**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunderserved_threshold <- 0.5\nphl_underserved <- phl_summary_clean |>\n  filter(dist_sch_mi > underserved_threshold)\nphl_underserved\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 48 features and 14 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -8378479 ymin: 4848009 xmax: -8344039 ymax: 4885181\nProjected CRS: WGS 84 / Pseudo-Mercator\nFirst 10 features:\n         GEOID tract_name median_incomeE median_incomeM total_popE total_popM\n1  42101034000        340          99181          12266       3185        505\n2  42101025800        258          48100          34245       1845        361\n3  42101025700        257          62516           5805       3737        483\n4  42101033400        334          54267           3967       5457        862\n5  42101005600         56          34523          18296       1138        294\n6  42101020800        208          70560          16378       2528        332\n7  42101033900        339          55636          13813       3066        455\n8  42101002000         20         103611          32944       2028        256\n9  42101006600         66          32946          12664       3396        937\n10 42101036502     365.02          93879          26171       4284        609\n   child_popE child_popM pct_child pct_poverty pct_white pct_black pct_hispanic\n1         494  172.71653     15.51       98.71     59.40     12.65        16.14\n2         315  125.25973     17.07      100.00      4.44     79.19         1.63\n3         360  146.19166      9.63      100.00     51.38     37.94         2.27\n4        1071  317.07255     19.63       94.17     44.58     19.15        13.16\n5         117   89.61027     10.28      100.00      4.39     87.26         4.22\n6         348  164.31981     13.77       84.77     41.93     30.85         8.47\n7         631  173.05202     20.58      100.00     47.95     28.70        16.70\n8          77   50.68530      3.80       99.61     34.71     40.48         2.12\n9         907  378.09126     26.71       99.32      4.45     84.48         1.33\n10        898  276.33675     20.96      100.00     86.34      0.61         7.49\n                         geometry dist_sch_mi\n1  MULTIPOLYGON (((-8357830 48...   0.6127870\n2  MULTIPOLYGON (((-8369941 48...   0.5517984\n3  MULTIPOLYGON (((-8371323 48...   0.5336515\n4  MULTIPOLYGON (((-8355714 48...   0.5674587\n5  MULTIPOLYGON (((-8376692 48...   0.8353058\n6  MULTIPOLYGON (((-8371495 48...   0.5025070\n7  MULTIPOLYGON (((-8359016 48...   0.7099034\n8  MULTIPOLYGON (((-8369917 48...   0.6723388\n9  MULTIPOLYGON (((-8375343 48...   0.5487150\n10 MULTIPOLYGON (((-8350125 48...   0.7215613\n```\n\n\n:::\n\n```{.r .cell-code}\n# Map Visualization\nggplot() + \n  geom_sf(data = phl_summary, fill = \"gray95\", color = \"black\", linewidth = 0.1, inherit.aes = FALSE) +\n  geom_sf(data = phl_underserved, aes(fill = pct_poverty)) +\n  geom_sf(data = phl_school_points, color = \"black\", size = 0.5, alpha = 0.75) +\n  scale_fill_continuous() + \n  labs(\n    title = \"Philadelphia Tracts Underserved by Schools\",\n    fill = \"Poverty %\") + \n  theme_void()\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\n**Analysis requirements:**\n\n-   Clear code comments explaining each step\n\n-   Appropriate CRS transformations\n\n-   Summary statistics or counts\n\n-   At least one map showing your findings\n\n-   Brief interpretation of results (3-5 sentences)\n\n**Your interpretation:**\n\n*\\[Write your findings here\\]*\n\n## Finally - A few comments about your incorporation of feedback!\n\nTake a few moments to clean up your markdown document and then write a line or\ntwo or three about how you may have incorporated feedback that you received\nafter your first assignment.\n\n*TA Feedback from Lab 1:*\n\n1.  Hide the setup code block. The Census API key is not supposed to be shared\n    publicly.\n2.  Printing in Console instead of RMD: if you want to print something, provide\n    a brief explanation\n\n--------------------------------------------------------------------------------\n\n## Submission Requirements\n\n**What to submit:**\n\n1.  **Rendered HTML document posted to your course portfolio** with all code,\n    outputs, maps, and text\n    -   Use `embed-resources: true` in YAML so it's a single file\n    -   All code should run without errors\n    -   All maps and charts should display correctly\n\n**File naming:** `LastName_FirstName_Assignment2.html` and\n`LastName_FirstName_Assignment2.qmd`\n\n--------------------------------------------------------------------------------\n",
    "supporting": [
      "assignment2_template_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}