<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.23">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jed Chew">
<meta name="dcterms.date" content="2025-09-29">

<title>Assignment 1: Census Data Quality for Policy Decisions – Jed Chew - MUSA 5080 Portfolio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-1fe81d0376b2c50856e68e651e390326.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-e31584831b205ffbb2d98406f31c2a5b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Jed Chew - MUSA 5080 Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-weekly-notes" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Weekly Notes</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-weekly-notes">    
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-01-notes.html">
 <span class="dropdown-text">Week 1 Notes - Course Introduction</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-02-notes.html">
 <span class="dropdown-text">Week 2 Notes - Algorithmic Decision Making &amp; Census Data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-03-notes.html">
 <span class="dropdown-text">Week 3 Notes - Data Viz and Exploratory Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-03-notes.html">
 <span class="dropdown-text">Week 3 Notes - Data Viz and Exploratory Analysis</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-labs" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Labs</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-labs">    
        <li>
    <a class="dropdown-item" href="../../labs/lab_0/scripts/lab0_template.html">
 <span class="dropdown-text">Lab 0: Getting Started with dplyr</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../labs/lab_1/assignment1_template.html">
 <span class="dropdown-text">Assignment 1: Census Data Quality for Policy Decisions</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#assignment-overview" id="toc-assignment-overview" class="nav-link active" data-scroll-target="#assignment-overview">Assignment Overview</a>
  <ul class="collapse">
  <li><a href="#scenario" id="toc-scenario" class="nav-link" data-scroll-target="#scenario">Scenario</a></li>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  <li><a href="#submission-instructions" id="toc-submission-instructions" class="nav-link" data-scroll-target="#submission-instructions">Submission Instructions</a></li>
  </ul></li>
  <li><a href="#part-1-portfolio-integration" id="toc-part-1-portfolio-integration" class="nav-link" data-scroll-target="#part-1-portfolio-integration">Part 1: Portfolio Integration</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#part-2-county-level-resource-assessment" id="toc-part-2-county-level-resource-assessment" class="nav-link" data-scroll-target="#part-2-county-level-resource-assessment">Part 2: County-Level Resource Assessment</a>
  <ul class="collapse">
  <li><a href="#data-retrieval" id="toc-data-retrieval" class="nav-link" data-scroll-target="#data-retrieval">2.1 Data Retrieval</a></li>
  <li><a href="#data-quality-assessment" id="toc-data-quality-assessment" class="nav-link" data-scroll-target="#data-quality-assessment">2.2 Data Quality Assessment</a></li>
  <li><a href="#high-uncertainty-counties" id="toc-high-uncertainty-counties" class="nav-link" data-scroll-target="#high-uncertainty-counties">2.3 High Uncertainty Counties</a></li>
  </ul></li>
  <li><a href="#part-3-neighborhood-level-analysis" id="toc-part-3-neighborhood-level-analysis" class="nav-link" data-scroll-target="#part-3-neighborhood-level-analysis">Part 3: Neighborhood-Level Analysis</a>
  <ul class="collapse">
  <li><a href="#focus-area-selection" id="toc-focus-area-selection" class="nav-link" data-scroll-target="#focus-area-selection">3.1 Focus Area Selection</a></li>
  <li><a href="#tract-level-demographics" id="toc-tract-level-demographics" class="nav-link" data-scroll-target="#tract-level-demographics">3.2 Tract-Level Demographics</a></li>
  <li><a href="#demographic-analysis" id="toc-demographic-analysis" class="nav-link" data-scroll-target="#demographic-analysis">3.3 Demographic Analysis</a></li>
  </ul></li>
  <li><a href="#part-4-comprehensive-data-quality-evaluation" id="toc-part-4-comprehensive-data-quality-evaluation" class="nav-link" data-scroll-target="#part-4-comprehensive-data-quality-evaluation">Part 4: Comprehensive Data Quality Evaluation</a>
  <ul class="collapse">
  <li><a href="#moe-analysis-for-demographic-variables" id="toc-moe-analysis-for-demographic-variables" class="nav-link" data-scroll-target="#moe-analysis-for-demographic-variables">4.1 MOE Analysis for Demographic Variables</a></li>
  <li><a href="#pattern-analysis" id="toc-pattern-analysis" class="nav-link" data-scroll-target="#pattern-analysis">4.2 Pattern Analysis</a></li>
  </ul></li>
  <li><a href="#part-5-policy-recommendations" id="toc-part-5-policy-recommendations" class="nav-link" data-scroll-target="#part-5-policy-recommendations">Part 5: Policy Recommendations</a>
  <ul class="collapse">
  <li><a href="#analysis-integration-and-professional-summary" id="toc-analysis-integration-and-professional-summary" class="nav-link" data-scroll-target="#analysis-integration-and-professional-summary">5.1 Analysis Integration and Professional Summary</a></li>
  <li><a href="#specific-recommendations" id="toc-specific-recommendations" class="nav-link" data-scroll-target="#specific-recommendations">6.3 Specific Recommendations</a></li>
  <li><a href="#questions-for-further-investigation" id="toc-questions-for-further-investigation" class="nav-link" data-scroll-target="#questions-for-further-investigation">Questions for Further Investigation</a></li>
  </ul></li>
  <li><a href="#technical-notes" id="toc-technical-notes" class="nav-link" data-scroll-target="#technical-notes">Technical Notes</a>
  <ul class="collapse">
  <li><a href="#submission-checklist" id="toc-submission-checklist" class="nav-link" data-scroll-target="#submission-checklist">Submission Checklist</a></li>
  </ul></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Assignment 1: Census Data Quality for Policy Decisions</h1>
<p class="subtitle lead">Evaluating Data Reliability for Algorithmic Decision-Making</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jed Chew </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 29, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="assignment-overview" class="level1">
<h1>Assignment Overview</h1>
<section id="scenario" class="level2">
<h2 class="anchored" data-anchor-id="scenario">Scenario</h2>
<p>You are a data analyst for the <strong>New York Department of Human Services</strong>. The department is considering implementing an algorithmic system to identify communities that should receive priority for social service funding and outreach programs. Your supervisor has asked you to evaluate the quality and reliability of available census data to inform this decision.</p>
<p>Drawing on our Week 2 discussion of algorithmic bias, you need to assess not just what the data shows, but how reliable it is and what communities might be affected by data quality issues.</p>
</section>
<section id="learning-objectives" class="level2">
<h2 class="anchored" data-anchor-id="learning-objectives">Learning Objectives</h2>
<ul>
<li>Apply dplyr functions to real census data for policy analysis</li>
<li>Evaluate data quality using margins of error</li>
<li>Connect technical analysis to algorithmic decision-making</li>
<li>Identify potential equity implications of data reliability issues</li>
<li>Create professional documentation for policy stakeholders</li>
</ul>
</section>
<section id="submission-instructions" class="level2">
<h2 class="anchored" data-anchor-id="submission-instructions">Submission Instructions</h2>
<p><strong>Submit by posting your updated portfolio link on Canvas.</strong> Your assignment should be accessible at <code>your-portfolio-url/assignments/assignment_1/</code></p>
<p>Make sure to update your <code>_quarto.yml</code> navigation to include this assignment under an “Assignments” menu.</p>
</section>
</section>
<section id="part-1-portfolio-integration" class="level1">
<h1>Part 1: Portfolio Integration</h1>
<p>Create this assignment in your portfolio repository under an <code>assignments/assignment_1/</code> folder structure. Update your navigation menu to include:</p>
<pre><code>- text: Assignments
  menu:
    - href: assignments/assignment_1/your_file_name.qmd
      text: "Assignment 1: Census Data Exploration"</code></pre>
<p>If there is a special character like comma, you need use double quote mark so that the quarto can identify this as text</p>
</section>
<section id="setup" class="level1">
<h1>Setup</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required packages (hint: you need tidycensus, tidyverse, and knitr)</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidycensus)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Set your Census API key</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">census_api_key</span>(<span class="st">"fe841b7ef0aa73d9579f0517bd1c8f26d33c789b"</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Choose your state for analysis - assign it to a variable called my_state</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>State Selection:</strong> I have chosen <strong>New York State</strong> for this analysis because I will be working in New York City post-graduation.</p>
</section>
<section id="part-2-county-level-resource-assessment" class="level1">
<h1>Part 2: County-Level Resource Assessment</h1>
<section id="data-retrieval" class="level2">
<h2 class="anchored" data-anchor-id="data-retrieval">2.1 Data Retrieval</h2>
<p><strong>Your Task:</strong> Use <code>get_acs()</code> to retrieve county-level data for your chosen state.</p>
<p><strong>Requirements:</strong><br>
- Geography: county level<br>
- Variables: median household income (B19013_001) and total population (B01003_001)<br>
- Year: 2022<br>
- Survey: acs5<br>
- Output format: wide</p>
<p><strong>Hint:</strong> Remember to give your variables descriptive names using the <code>variables = c(name = "code")</code> syntax.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Write your get_acs() code here</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>ny_data <span class="ot">&lt;-</span> <span class="fu">get_acs</span>(</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">geography =</span> <span class="st">"county"</span>,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">variables =</span> <span class="fu">c</span>(</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_pop =</span> <span class="st">"B01003_001"</span>,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_income =</span> <span class="st">"B19013_001"</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">state =</span> <span class="st">"NY"</span>,</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">year =</span> <span class="dv">2022</span>,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">survey =</span> <span class="st">"acs5"</span>,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">output =</span> <span class="st">"wide"</span> </span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean the county names to remove state name and "County" </span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: use mutate() with str_remove()</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>ny_clean <span class="ot">&lt;-</span> ny_data <span class="sc">|&gt;</span> </span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Remove state name from county names</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">county_name =</span> <span class="fu">str_remove</span>(NAME, <span class="st">", New York"</span>),</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Remove "County" word</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">county_name =</span> <span class="fu">str_remove</span>(county_name, <span class="st">" County"</span>)</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the first few rows</span></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ny_clean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 7
  GEOID NAME     total_popE total_popM median_incomeE median_incomeM county_name
  &lt;chr&gt; &lt;chr&gt;         &lt;dbl&gt;      &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt; &lt;chr&gt;      
1 36001 Albany …     315041         NA          78829           2049 Albany     
2 36003 Allegan…      47222         NA          58725           1965 Allegany   
3 36005 Bronx C…    1443229         NA          47036            890 Bronx      
4 36007 Broome …     198365         NA          58317           1761 Broome     
5 36009 Cattara…      77000         NA          56889           1778 Cattaraugus
6 36011 Cayuga …      76171         NA          63227           2736 Cayuga     </code></pre>
</div>
</div>
</section>
<section id="data-quality-assessment" class="level2">
<h2 class="anchored" data-anchor-id="data-quality-assessment">2.2 Data Quality Assessment</h2>
<p><strong>Your Task:</strong> Calculate margin of error percentages and create reliability categories.</p>
<p><strong>Requirements:</strong></p>
<p>- Calculate MOE percentage: (margin of error / estimate) * 100<br>
- Create reliability categories:<br>
- High Confidence: MOE &lt; 5%<br>
- Moderate Confidence: MOE 5-10%<br>
- Low Confidence: MOE &gt; 10%<br>
- Create a flag for unreliable estimates (MOE &gt; 10%)</p>
<p><strong>Hint:</strong> Use <code>mutate()</code> with <code>case_when()</code> for the categories.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate MOE percentage and reliability categories using mutate()</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>ny_reliability <span class="ot">&lt;-</span> ny_clean <span class="sc">|&gt;</span> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">moe_percent =</span> <span class="fu">round</span>((median_incomeM <span class="sc">/</span> median_incomeE) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>),</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create reliability categories</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">reliability =</span> <span class="fu">case_when</span>(</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>      moe_percent <span class="sc">&lt;</span> <span class="dv">5</span> <span class="sc">~</span> <span class="st">"High"</span>,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>      moe_percent <span class="sc">&gt;=</span> <span class="dv">5</span> <span class="sc">&amp;</span> moe_percent <span class="sc">&lt;=</span> <span class="dv">10</span> <span class="sc">~</span> <span class="st">"Moderate"</span>,</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>      moe_percent <span class="sc">&gt;</span> <span class="dv">10</span> <span class="sc">~</span> <span class="st">"Low"</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>ny_reliability</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 62 × 9
   GEOID NAME    total_popE total_popM median_incomeE median_incomeM county_name
   &lt;chr&gt; &lt;chr&gt;        &lt;dbl&gt;      &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt; &lt;chr&gt;      
 1 36001 Albany…     315041         NA          78829           2049 Albany     
 2 36003 Allega…      47222         NA          58725           1965 Allegany   
 3 36005 Bronx …    1443229         NA          47036            890 Bronx      
 4 36007 Broome…     198365         NA          58317           1761 Broome     
 5 36009 Cattar…      77000         NA          56889           1778 Cattaraugus
 6 36011 Cayuga…      76171         NA          63227           2736 Cayuga     
 7 36013 Chauta…     127440         NA          54625           1754 Chautauqua 
 8 36015 Chemun…      83584         NA          61358           2475 Chemung    
 9 36017 Chenan…      47096         NA          61741           2526 Chenango   
10 36019 Clinto…      79839         NA          67097           2802 Clinton    
# ℹ 52 more rows
# ℹ 2 more variables: moe_percent &lt;dbl&gt;, reliability &lt;chr&gt;</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a summary showing count of counties in each reliability category</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: use count() and mutate() to add percentages</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">count</span>(ny_reliability, reliability)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  reliability     n
  &lt;chr&gt;       &lt;int&gt;
1 High           56
2 Low             1
3 Moderate        5</code></pre>
</div>
</div>
</section>
<section id="high-uncertainty-counties" class="level2">
<h2 class="anchored" data-anchor-id="high-uncertainty-counties">2.3 High Uncertainty Counties</h2>
<p><strong>Your Task:</strong> Identify the 5 counties with the highest MOE percentages.</p>
<p><strong>Requirements:</strong> - Sort by MOE percentage (highest first) - Select the top 5 counties - Display: county name, median income, margin of error, MOE percentage, reliability category - Format as a professional table using <code>kable()</code></p>
<p><strong>Hint:</strong> Use <code>arrange()</code>, <code>slice()</code>, and <code>select()</code> functions.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create table of top 5 counties by MOE percentage</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>high_uncertainty <span class="ot">&lt;-</span> ny_reliability <span class="sc">|&gt;</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(moe_percent)) <span class="sc">|&gt;</span> </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>) <span class="sc">|&gt;</span> </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(county_name, median_incomeE, median_incomeM, moe_percent, reliability)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>high_uncertainty</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 5
  county_name median_incomeE median_incomeM moe_percent reliability
  &lt;chr&gt;                &lt;dbl&gt;          &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;      
1 Hamilton             66891           7622       11.4  Low        
2 Schuyler             61316           5818        9.49 Moderate   
3 Greene               70294           4341        6.18 Moderate   
4 Yates                63974           3733        5.84 Moderate   
5 Essex                68090           3590        5.27 Moderate   </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Format as table with kable() - include appropriate column names and caption</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(high_uncertainty,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"County"</span>, <span class="st">"Median Income"</span>, <span class="st">"MOE"</span>, <span class="st">"MOE %"</span>, <span class="st">"Reliability"</span>),</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"NY Counties with Greatest Income Data Uncertainty"</span>,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">format.args =</span> <span class="fu">list</span>(<span class="at">big.mark =</span> <span class="st">","</span>)) <span class="co">#large nums have 000s separators</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>NY Counties with Greatest Income Data Uncertainty</caption>
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: right;">Median Income</th>
<th style="text-align: right;">MOE</th>
<th style="text-align: right;">MOE %</th>
<th style="text-align: left;">Reliability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Hamilton</td>
<td style="text-align: right;">66,891</td>
<td style="text-align: right;">7,622</td>
<td style="text-align: right;">11.39</td>
<td style="text-align: left;">Low</td>
</tr>
<tr class="even">
<td style="text-align: left;">Schuyler</td>
<td style="text-align: right;">61,316</td>
<td style="text-align: right;">5,818</td>
<td style="text-align: right;">9.49</td>
<td style="text-align: left;">Moderate</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Greene</td>
<td style="text-align: right;">70,294</td>
<td style="text-align: right;">4,341</td>
<td style="text-align: right;">6.18</td>
<td style="text-align: left;">Moderate</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yates</td>
<td style="text-align: right;">63,974</td>
<td style="text-align: right;">3,733</td>
<td style="text-align: right;">5.84</td>
<td style="text-align: left;">Moderate</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Essex</td>
<td style="text-align: right;">68,090</td>
<td style="text-align: right;">3,590</td>
<td style="text-align: right;">5.27</td>
<td style="text-align: left;">Moderate</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Data Quality Commentary:</strong> Algorithmic decision-making at the New York state-level cannot occur with one broad brush. While 56 out of 62 NY counties are classified as having highly reliable income data, 5 counties are classified as having moderate reliability and 1 county is classified as having low reliability. As shown in the table below, a possible reason for these 6 counties having low/moderate reliability could be their relatively smaller populations compared to other counties. Hence, special attention must be paid to these 6 counties, with algorithmic tools to identify communities that should receive priority for social service funding and outreach programs being complemented by qualitative on-the-ground outreach and interviews with local residents.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>high_uncertainty_pop <span class="ot">&lt;-</span> ny_reliability <span class="sc">|&gt;</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(moe_percent)) <span class="sc">|&gt;</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>) <span class="sc">|&gt;</span> </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(county_name, total_popE, median_incomeE, moe_percent, reliability)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>high_uncertainty_pop</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 5
  county_name total_popE median_incomeE moe_percent reliability
  &lt;chr&gt;            &lt;dbl&gt;          &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;      
1 Hamilton          5090          66891       11.4  Low        
2 Schuyler         17855          61316        9.49 Moderate   
3 Greene           48067          70294        6.18 Moderate   
4 Yates            24713          63974        5.84 Moderate   
5 Essex            37314          68090        5.27 Moderate   </code></pre>
</div>
</div>
</section>
</section>
<section id="part-3-neighborhood-level-analysis" class="level1">
<h1>Part 3: Neighborhood-Level Analysis</h1>
<section id="focus-area-selection" class="level2">
<h2 class="anchored" data-anchor-id="focus-area-selection">3.1 Focus Area Selection</h2>
<p><strong>Your Task:</strong> Select 2-3 counties from your reliability analysis for detailed tract-level study.</p>
<p><strong>Strategy:</strong> Choose counties that represent different reliability levels (e.g., 1 high confidence, 1 moderate, 1 low confidence) to compare how data quality varies.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use filter() to select 2-3 counties from your county_reliability data</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Store the selected counties in a variable called selected_counties</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>selected_counties <span class="ot">&lt;-</span> ny_reliability <span class="sc">|&gt;</span> </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_min</span>(moe_percent, <span class="at">n =</span> <span class="dv">1</span>, <span class="at">by =</span> reliability)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>selected_counties</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 9
  GEOID NAME     total_popE total_popM median_incomeE median_incomeM county_name
  &lt;chr&gt; &lt;chr&gt;         &lt;dbl&gt;      &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt; &lt;chr&gt;      
1 36081 Queens …    2360826         NA          82431            873 Queens     
2 36099 Seneca …      33651         NA          64050           3355 Seneca     
3 36041 Hamilto…       5090         NA          66891           7622 Hamilton   
# ℹ 2 more variables: moe_percent &lt;dbl&gt;, reliability &lt;chr&gt;</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the selected counties with their key characteristics</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Show: county name, median income, MOE percentage, reliability category</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(selected_counties, county_name, median_incomeE, moe_percent, reliability)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  county_name median_incomeE moe_percent reliability
  &lt;chr&gt;                &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;      
1 Queens               82431        1.06 High       
2 Seneca               64050        5.24 Moderate   
3 Hamilton             66891       11.4  Low        </code></pre>
</div>
</div>
<p><strong>Comment on the output:</strong> There is a significant difference between the margin of error for different counties. For example, Queens County has a margin of error percentage of only 1.06%, whereas Hamilton County has a margin of error percentage of 11.39%.</p>
</section>
<section id="tract-level-demographics" class="level2">
<h2 class="anchored" data-anchor-id="tract-level-demographics">3.2 Tract-Level Demographics</h2>
<p><strong>Your Task:</strong> Get demographic data for census tracts in your selected counties.</p>
<p><strong>Requirements:</strong></p>
<ul>
<li>Geography: tract level</li>
<li>Variables: white alone (B03002_003), Black/African American (B03002_004), Hispanic/Latino (B03002_012), total population (B03002_001)</li>
<li>Use the same state and year as before</li>
<li>Output format: wide</li>
</ul>
<p><strong>Challenge:</strong> You’ll need county codes, not names. Look at the GEOID patterns in your county data for hints.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define your race/ethnicity variables with descriptive names</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>race_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_pop =</span> <span class="st">"B03002_001"</span>,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">White     =</span> <span class="st">"B03002_003"</span>,</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Black     =</span> <span class="st">"B03002_004"</span>,</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Hispanic  =</span> <span class="st">"B03002_012"</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Use get_acs() to retrieve tract-level data</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: You may need to specify county codes in the county parameter</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>tract_data <span class="ot">&lt;-</span> <span class="fu">get_acs</span>(</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">geography =</span> <span class="st">"tract"</span>,</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">variables =</span> race_vars,</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">state =</span> <span class="st">"NY"</span>,</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># GEOIDs for Queens, Seneca, and Hamilton Counties</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">county =</span> <span class="fu">c</span>(<span class="st">"081"</span>, <span class="st">"099"</span>, <span class="st">"041"</span>),</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">year =</span> <span class="dv">2022</span>,</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">survey =</span> <span class="st">"acs5"</span>,</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">output =</span> <span class="st">"wide"</span></span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>tract_data</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 740 × 10
   GEOID       NAME  total_popE total_popM WhiteE WhiteM BlackE BlackM HispanicE
   &lt;chr&gt;       &lt;chr&gt;      &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;
 1 36041950100 Cens…        922        156    817    145     23     18        43
 2 36041950300 Cens…       1063        229   1008    224      2      4         3
 3 36041950400 Cens…       1880        240   1740    225      6      8        48
 4 36041950500 Cens…       1225        144   1121    136     24     13         8
 5 36081000101 Cens…       5027        860   2086    492      0     19       592
 6 36081000102 Cens…       5966       1015   3144    760     39     47       459
 7 36081000103 Cens…          0         13      0     13      0     13         0
 8 36081000104 Cens…        371        110     65     67    169     58       125
 9 36081000200 Cens…       2553        551    273    104    203    172      1202
10 36081000400 Cens…       4738       1144    131     93    216    195      3327
# ℹ 730 more rows
# ℹ 1 more variable: HispanicM &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add readable tract and county name columns using str_extract() or similar</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>tract_clean <span class="ot">&lt;-</span> tract_data <span class="sc">|&gt;</span> </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(total_popE <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">|&gt;</span> <span class="co"># remove tracts with zero estimated population</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    NAME, </span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"tract_name"</span>, <span class="st">"county_name"</span>, <span class="st">"state_name"</span>), </span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">sep =</span> <span class="st">"; "</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">tract_name =</span> <span class="fu">str_remove</span>(tract_name, <span class="st">"Census Tract "</span>),</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">county_name =</span> <span class="fu">str_remove</span>(county_name, <span class="st">" County"</span>)</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>tract_clean</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 704 × 12
   GEOID   tract_name county_name state_name total_popE total_popM WhiteE WhiteM
   &lt;chr&gt;   &lt;chr&gt;      &lt;chr&gt;       &lt;chr&gt;           &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1 360419… 9501       Hamilton    New York          922        156    817    145
 2 360419… 9503       Hamilton    New York         1063        229   1008    224
 3 360419… 9504       Hamilton    New York         1880        240   1740    225
 4 360419… 9505       Hamilton    New York         1225        144   1121    136
 5 360810… 1.01       Queens      New York         5027        860   2086    492
 6 360810… 1.02       Queens      New York         5966       1015   3144    760
 7 360810… 1.04       Queens      New York          371        110     65     67
 8 360810… 2          Queens      New York         2553        551    273    104
 9 360810… 4          Queens      New York         4738       1144    131     93
10 360810… 6          Queens      New York         3890        777    346    179
# ℹ 694 more rows
# ℹ 4 more variables: BlackE &lt;dbl&gt;, BlackM &lt;dbl&gt;, HispanicE &lt;dbl&gt;,
#   HispanicM &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate percentage of each group using mutate()</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Create percentages for white, Black, and Hispanic populations</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>tract_clean <span class="ot">&lt;-</span> tract_clean <span class="sc">|&gt;</span> </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">percent_white =</span> <span class="fu">round</span>((WhiteE<span class="sc">/</span>total_popE) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>),</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">percent_black =</span> <span class="fu">round</span>((BlackE<span class="sc">/</span>total_popE) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>),</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">percent_hispanic =</span> <span class="fu">round</span>((HispanicE<span class="sc">/</span>total_popE) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>),</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>tract_clean</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 704 × 15
   GEOID   tract_name county_name state_name total_popE total_popM WhiteE WhiteM
   &lt;chr&gt;   &lt;chr&gt;      &lt;chr&gt;       &lt;chr&gt;           &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1 360419… 9501       Hamilton    New York          922        156    817    145
 2 360419… 9503       Hamilton    New York         1063        229   1008    224
 3 360419… 9504       Hamilton    New York         1880        240   1740    225
 4 360419… 9505       Hamilton    New York         1225        144   1121    136
 5 360810… 1.01       Queens      New York         5027        860   2086    492
 6 360810… 1.02       Queens      New York         5966       1015   3144    760
 7 360810… 1.04       Queens      New York          371        110     65     67
 8 360810… 2          Queens      New York         2553        551    273    104
 9 360810… 4          Queens      New York         4738       1144    131     93
10 360810… 6          Queens      New York         3890        777    346    179
# ℹ 694 more rows
# ℹ 7 more variables: BlackE &lt;dbl&gt;, BlackM &lt;dbl&gt;, HispanicE &lt;dbl&gt;,
#   HispanicM &lt;dbl&gt;, percent_white &lt;dbl&gt;, percent_black &lt;dbl&gt;,
#   percent_hispanic &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="demographic-analysis" class="level2">
<h2 class="anchored" data-anchor-id="demographic-analysis">3.3 Demographic Analysis</h2>
<p><strong>Your Task:</strong> Analyze the demographic patterns in your selected areas.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the tract with the highest percentage of Hispanic/Latino residents</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: use arrange() and slice() to get the top tract</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>tract_highest_hispanic <span class="ot">&lt;-</span> tract_clean <span class="sc">|&gt;</span> </span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(percent_hispanic)) <span class="sc">|&gt;</span> </span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(tract_name, county_name, total_popE, percent_hispanic)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>tract_highest_hispanic</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  tract_name county_name total_popE percent_hispanic
  &lt;chr&gt;      &lt;chr&gt;            &lt;dbl&gt;            &lt;dbl&gt;
1 407.01     Queens            3676             96.6</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate average demographics by county using group_by() and summarize()</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Show: number of tracts, average percentage for each racial/ethnic group</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>demo_county <span class="ot">&lt;-</span> tract_clean <span class="sc">|&gt;</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(county_name) <span class="sc">|&gt;</span> </span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">num_tracts =</span> <span class="fu">n</span>(),</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_white =</span> <span class="fu">round</span>(<span class="fu">mean</span>(percent_white), <span class="dv">2</span>),</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_black =</span> <span class="fu">round</span>(<span class="fu">mean</span>(percent_black), <span class="dv">2</span>),</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_hispanic =</span> <span class="fu">round</span>(<span class="fu">mean</span>(percent_hispanic), <span class="dv">2</span>)</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a nicely formatted table of your results using kable()</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(demo_county,</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"County Name"</span>, <span class="st">"# Tracts"</span>, <span class="st">"% White"</span>, <span class="st">"% Black"</span>, <span class="st">"% Hispanic"</span>),</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Average Demographics by County for Selected NY Counties"</span>,</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>      <span class="at">format.args =</span> <span class="fu">list</span>(<span class="at">big.mark =</span> <span class="st">","</span>)) <span class="co">#large nums have 000s separators</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Average Demographics by County for Selected NY Counties</caption>
<thead>
<tr class="header">
<th style="text-align: left;">County Name</th>
<th style="text-align: right;"># Tracts</th>
<th style="text-align: right;">% White</th>
<th style="text-align: right;">% Black</th>
<th style="text-align: right;">% Hispanic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Hamilton</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">91.88</td>
<td style="text-align: right;">1.24</td>
<td style="text-align: right;">2.04</td>
</tr>
<tr class="even">
<td style="text-align: left;">Queens</td>
<td style="text-align: right;">689</td>
<td style="text-align: right;">23.91</td>
<td style="text-align: right;">18.42</td>
<td style="text-align: right;">27.07</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Seneca</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">84.45</td>
<td style="text-align: right;">7.23</td>
<td style="text-align: right;">4.32</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="part-4-comprehensive-data-quality-evaluation" class="level1">
<h1>Part 4: Comprehensive Data Quality Evaluation</h1>
<section id="moe-analysis-for-demographic-variables" class="level2">
<h2 class="anchored" data-anchor-id="moe-analysis-for-demographic-variables">4.1 MOE Analysis for Demographic Variables</h2>
<p><strong>Your Task:</strong> Examine margins of error for demographic variables to see if some communities have less reliable data.</p>
<p><strong>Requirements:</strong></p>
<ul>
<li>Calculate MOE percentages for each demographic variable</li>
<li>Flag tracts where any demographic variable has MOE &gt; 15%</li>
<li>Create Summary Statistics</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate MOE percentages for white, Black, and Hispanic variables</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: use the same formula as before (margin/estimate * 100)</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>tract_reliability <span class="ot">&lt;-</span> tract_clean <span class="sc">|&gt;</span> </span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">moe_percent_white =</span> <span class="fu">round</span>((WhiteM<span class="sc">/</span>WhiteE) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>), </span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">moe_percent_black =</span> <span class="fu">round</span>((BlackM<span class="sc">/</span>BlackE) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>),</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">moe_percent_hispanic =</span> <span class="fu">round</span>((HispanicM<span class="sc">/</span>HispanicE) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a flag for tracts with high MOE on any demographic variable</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Use logical operators (| for OR) in an ifelse() statement</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>tract_reliability <span class="ot">&lt;-</span> tract_reliability <span class="sc">|&gt;</span> </span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">reliability =</span> <span class="fu">if_else</span>(</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>      moe_percent_white <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">|</span> moe_percent_black <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">|</span> moe_percent_hispanic <span class="sc">&gt;</span> <span class="dv">15</span>,</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Low"</span>,</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>      <span class="st">"High"</span></span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>tract_reliability</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 704 × 19
   GEOID   tract_name county_name state_name total_popE total_popM WhiteE WhiteM
   &lt;chr&gt;   &lt;chr&gt;      &lt;chr&gt;       &lt;chr&gt;           &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1 360419… 9501       Hamilton    New York          922        156    817    145
 2 360419… 9503       Hamilton    New York         1063        229   1008    224
 3 360419… 9504       Hamilton    New York         1880        240   1740    225
 4 360419… 9505       Hamilton    New York         1225        144   1121    136
 5 360810… 1.01       Queens      New York         5027        860   2086    492
 6 360810… 1.02       Queens      New York         5966       1015   3144    760
 7 360810… 1.04       Queens      New York          371        110     65     67
 8 360810… 2          Queens      New York         2553        551    273    104
 9 360810… 4          Queens      New York         4738       1144    131     93
10 360810… 6          Queens      New York         3890        777    346    179
# ℹ 694 more rows
# ℹ 11 more variables: BlackE &lt;dbl&gt;, BlackM &lt;dbl&gt;, HispanicE &lt;dbl&gt;,
#   HispanicM &lt;dbl&gt;, percent_white &lt;dbl&gt;, percent_black &lt;dbl&gt;,
#   percent_hispanic &lt;dbl&gt;, moe_percent_white &lt;dbl&gt;, moe_percent_black &lt;dbl&gt;,
#   moe_percent_hispanic &lt;dbl&gt;, reliability &lt;chr&gt;</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create summary statistics showing how many tracts have data quality issues</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">count</span>(tract_reliability, reliability)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  reliability     n
  &lt;chr&gt;       &lt;int&gt;
1 Low           704</code></pre>
</div>
</div>
</section>
<section id="pattern-analysis" class="level2">
<h2 class="anchored" data-anchor-id="pattern-analysis">4.2 Pattern Analysis</h2>
<p><strong>Your Task:</strong> Investigate whether data quality problems are randomly distributed or concentrated in certain types of communities.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Group tracts by whether they have high MOE issues</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate average characteristics for each group:</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="co"># - population size, demographic percentages</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Use group_by() and summarize() to create this comparison</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a professional table showing the patterns</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Pattern Analysis:</strong> As shown in the tibble in Section 4.1 above, all 704 census tracts in my selected NY counties were flagged for low reliability because one of their demographic variable has a MOE &gt; 15%. I was initially very confused by this, because I had deliberately chosen one county from each reliability category earlier (as shown below). However, I realized that the MOE calculation in earlier sections was based on median income rather than population. After discussing with Dr.&nbsp;Delmelle during office hours, some reasons that we came up with for these high MOEs include low population (especially for Hamilton County) or non-residential census tracts (such as LaGuardia Airport or Citi Field in Queens County).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(selected_counties, county_name, median_incomeE, moe_percent, reliability)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  county_name median_incomeE moe_percent reliability
  &lt;chr&gt;                &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;      
1 Queens               82431        1.06 High       
2 Seneca               64050        5.24 Moderate   
3 Hamilton             66891       11.4  Low        </code></pre>
</div>
</div>
</section>
</section>
<section id="part-5-policy-recommendations" class="level1">
<h1>Part 5: Policy Recommendations</h1>
<section id="analysis-integration-and-professional-summary" class="level2">
<h2 class="anchored" data-anchor-id="analysis-integration-and-professional-summary">5.1 Analysis Integration and Professional Summary</h2>
<p><strong>Your Task:</strong> Write an executive summary that integrates findings from all four analyses.</p>
<p><strong>Executive Summary Requirements:</strong></p>
<p>1. <strong>Overall Pattern Identification</strong>: What are the systematic patterns across all your analyses?</p>
<p>2. <strong>Equity Assessment</strong>: Which communities face the greatest risk of algorithmic bias based on your findings?</p>
<p>3. <strong>Root Cause Analysis</strong>: What underlying factors drive both data quality issues and bias risk?</p>
<p>4. <strong>Strategic Recommendations</strong>: What should the Department implement to address these systematic issues?</p>
<p><strong>Executive Summary:</strong></p>
<p><strong>[Overall Pattern Identification]</strong> My analyses found that county-level indicators are generally high-reliability, but tract-level results show wide variance in MOE%, especially for demographic estimates such as race/ethnicity.</p>
<p><strong>[Equity Assessment]</strong> Communities in tracts with high MOE% (threshold of ~15%) for key demographics and income indicators face the greatest risk of algorithmic bias because small sampling error can flip decision regarding eligibility or prioritization for social service and outreach programs. This risk concentrates in low-population tracts and often in places where Black and Hispanic counts are small minorities at the tract level.</p>
<p><strong>[Root Cause Analysis]</strong> The root cause of this high MOE%s is likely the ACS sampling variability. Every year, the ACS surveys about 1 in 40 housing units, and the 5-year estimates essentially incorporate the past 5 years of these non-overlapping sampling to recreate the longform of the decennial census. However, this could result in major tract-level changes (such as redevelopment) or a redrawing of tract boundaries being smoothed over when looking at the 5-year estimates, leading to substantial noise in the data that shows in up high MOE% for limited sample sizes.</p>
<p><strong>[Strategic Recommendations]</strong> NY Department of Human Services should adopt a tiered reliability policy (e.g., High = proceed; Moderate = monitor with additional oversight; Low = human review or supplemental data) before applying thresholds. Pair this with routine fairness audits and stability checks, prioritize five-year ACS estimates where appropriate, and fund targeted data collection or administrative-data linkages in the selected tracts that repeatedly produce the highest MOE% to reduce structural uncertainty of algorithmic decisions over time.</p>
</section>
<section id="specific-recommendations" class="level2">
<h2 class="anchored" data-anchor-id="specific-recommendations">6.3 Specific Recommendations</h2>
<p><strong>Your Task:</strong> Create a decision framework for algorithm implementation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a summary table using your county reliability data</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Include: county name, median income, MOE percentage, reliability category</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a new column with algorithm recommendations using case_when():</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="co"># - High Confidence: "Safe for algorithmic decisions"</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="co"># - Moderate Confidence: "Use with caution - monitor outcomes"  </span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="co"># - Low Confidence: "Requires manual review or additional data"</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Format as a professional table with kable()</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>county_summary <span class="ot">&lt;-</span> ny_reliability <span class="sc">|&gt;</span> </span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(county_name, median_incomeE, moe_percent, reliability) <span class="sc">|&gt;</span> </span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(moe_percent) <span class="sc">|&gt;</span> </span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">recommendation =</span> <span class="fu">case_when</span>(</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>      reliability <span class="sc">==</span> <span class="st">"High"</span> <span class="sc">~</span> <span class="st">"Safe for algorithmic decisions"</span>,</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>      reliability <span class="sc">==</span> <span class="st">"Moderate"</span> <span class="sc">~</span> <span class="st">"Use with caution - monitor outcomes"</span>,  </span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>      reliability <span class="sc">==</span> <span class="st">"Low"</span> <span class="sc">~</span> <span class="st">"Requires manual review or additional data"</span></span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(county_summary,</span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"County"</span>, <span class="st">"Median Income"</span>, <span class="st">"MOE"</span>, <span class="st">"Reliability"</span>, <span class="st">"Recommendation"</span>),</span>
<span id="cb34-23"><a href="#cb34-23" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="fu">toupper</span>(<span class="st">"Recommended Algorithm for NY Counties"</span>),</span>
<span id="cb34-24"><a href="#cb34-24" aria-hidden="true" tabindex="-1"></a>      <span class="at">format.args =</span> <span class="fu">list</span>(<span class="at">big.mark =</span> <span class="st">","</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>RECOMMENDED ALGORITHM FOR NY COUNTIES</caption>
<colgroup>
<col style="width: 14%">
<col style="width: 16%">
<col style="width: 6%">
<col style="width: 13%">
<col style="width: 48%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: right;">Median Income</th>
<th style="text-align: right;">MOE</th>
<th style="text-align: left;">Reliability</th>
<th style="text-align: left;">Recommendation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Queens</td>
<td style="text-align: right;">82,431</td>
<td style="text-align: right;">1.06</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Erie</td>
<td style="text-align: right;">68,014</td>
<td style="text-align: right;">1.18</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Suffolk</td>
<td style="text-align: right;">122,498</td>
<td style="text-align: right;">1.18</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kings</td>
<td style="text-align: right;">74,692</td>
<td style="text-align: right;">1.27</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Monroe</td>
<td style="text-align: right;">71,450</td>
<td style="text-align: right;">1.35</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nassau</td>
<td style="text-align: right;">137,709</td>
<td style="text-align: right;">1.39</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Westchester</td>
<td style="text-align: right;">114,651</td>
<td style="text-align: right;">1.56</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Onondaga</td>
<td style="text-align: right;">71,479</td>
<td style="text-align: right;">1.57</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">New York</td>
<td style="text-align: right;">99,880</td>
<td style="text-align: right;">1.78</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bronx</td>
<td style="text-align: right;">47,036</td>
<td style="text-align: right;">1.89</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Orange</td>
<td style="text-align: right;">91,806</td>
<td style="text-align: right;">1.94</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Saratoga</td>
<td style="text-align: right;">97,038</td>
<td style="text-align: right;">2.26</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rensselaer</td>
<td style="text-align: right;">83,734</td>
<td style="text-align: right;">2.27</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Albany</td>
<td style="text-align: right;">78,829</td>
<td style="text-align: right;">2.60</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Richmond</td>
<td style="text-align: right;">96,185</td>
<td style="text-align: right;">2.60</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dutchess</td>
<td style="text-align: right;">94,578</td>
<td style="text-align: right;">2.66</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Niagara</td>
<td style="text-align: right;">65,882</td>
<td style="text-align: right;">2.67</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Steuben</td>
<td style="text-align: right;">62,506</td>
<td style="text-align: right;">2.87</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rockland</td>
<td style="text-align: right;">106,173</td>
<td style="text-align: right;">2.88</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ontario</td>
<td style="text-align: right;">76,603</td>
<td style="text-align: right;">2.94</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Broome</td>
<td style="text-align: right;">58,317</td>
<td style="text-align: right;">3.02</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Schenectady</td>
<td style="text-align: right;">75,056</td>
<td style="text-align: right;">3.03</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wayne</td>
<td style="text-align: right;">71,007</td>
<td style="text-align: right;">3.10</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cattaraugus</td>
<td style="text-align: right;">56,889</td>
<td style="text-align: right;">3.13</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chautauqua</td>
<td style="text-align: right;">54,625</td>
<td style="text-align: right;">3.21</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Oswego</td>
<td style="text-align: right;">65,054</td>
<td style="text-align: right;">3.26</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Oneida</td>
<td style="text-align: right;">66,402</td>
<td style="text-align: right;">3.27</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Allegany</td>
<td style="text-align: right;">58,725</td>
<td style="text-align: right;">3.35</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wyoming</td>
<td style="text-align: right;">65,066</td>
<td style="text-align: right;">3.38</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Columbia</td>
<td style="text-align: right;">81,741</td>
<td style="text-align: right;">3.39</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Washington</td>
<td style="text-align: right;">68,703</td>
<td style="text-align: right;">3.41</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">St.&nbsp;Lawrence</td>
<td style="text-align: right;">58,339</td>
<td style="text-align: right;">3.47</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Montgomery</td>
<td style="text-align: right;">58,033</td>
<td style="text-align: right;">3.63</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jefferson</td>
<td style="text-align: right;">62,782</td>
<td style="text-align: right;">3.64</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Delaware</td>
<td style="text-align: right;">58,338</td>
<td style="text-align: right;">3.67</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Schoharie</td>
<td style="text-align: right;">71,479</td>
<td style="text-align: right;">3.96</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Livingston</td>
<td style="text-align: right;">70,443</td>
<td style="text-align: right;">3.99</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tioga</td>
<td style="text-align: right;">70,427</td>
<td style="text-align: right;">3.99</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tompkins</td>
<td style="text-align: right;">69,995</td>
<td style="text-align: right;">4.01</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chemung</td>
<td style="text-align: right;">61,358</td>
<td style="text-align: right;">4.03</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Putnam</td>
<td style="text-align: right;">120,970</td>
<td style="text-align: right;">4.03</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Madison</td>
<td style="text-align: right;">68,869</td>
<td style="text-align: right;">4.04</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chenango</td>
<td style="text-align: right;">61,741</td>
<td style="text-align: right;">4.09</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lewis</td>
<td style="text-align: right;">64,401</td>
<td style="text-align: right;">4.16</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Clinton</td>
<td style="text-align: right;">67,097</td>
<td style="text-align: right;">4.18</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cayuga</td>
<td style="text-align: right;">63,227</td>
<td style="text-align: right;">4.33</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sullivan</td>
<td style="text-align: right;">67,841</td>
<td style="text-align: right;">4.35</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fulton</td>
<td style="text-align: right;">60,557</td>
<td style="text-align: right;">4.37</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cortland</td>
<td style="text-align: right;">65,029</td>
<td style="text-align: right;">4.42</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Otsego</td>
<td style="text-align: right;">65,778</td>
<td style="text-align: right;">4.51</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ulster</td>
<td style="text-align: right;">77,197</td>
<td style="text-align: right;">4.52</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Genesee</td>
<td style="text-align: right;">68,178</td>
<td style="text-align: right;">4.57</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Warren</td>
<td style="text-align: right;">74,531</td>
<td style="text-align: right;">4.74</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Herkimer</td>
<td style="text-align: right;">68,104</td>
<td style="text-align: right;">4.79</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Franklin</td>
<td style="text-align: right;">60,270</td>
<td style="text-align: right;">4.81</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Orleans</td>
<td style="text-align: right;">61,069</td>
<td style="text-align: right;">4.89</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Seneca</td>
<td style="text-align: right;">64,050</td>
<td style="text-align: right;">5.24</td>
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Essex</td>
<td style="text-align: right;">68,090</td>
<td style="text-align: right;">5.27</td>
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Yates</td>
<td style="text-align: right;">63,974</td>
<td style="text-align: right;">5.84</td>
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Greene</td>
<td style="text-align: right;">70,294</td>
<td style="text-align: right;">6.18</td>
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Schuyler</td>
<td style="text-align: right;">61,316</td>
<td style="text-align: right;">9.49</td>
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hamilton</td>
<td style="text-align: right;">66,891</td>
<td style="text-align: right;">11.39</td>
<td style="text-align: left;">Low</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Key Recommendations:</strong></p>
<p><strong>Your Task:</strong> Use your analysis results to provide specific guidance to the department.</p>
<ol type="1">
<li><p><strong>Counties suitable for immediate algorithmic implementation:</strong> [List counties with high confidence data and explain why they’re appropriate]</p>
<p>The 56 NY counties listed below have MOE percentages of less than 5%, hence we classify the income data as having “<em>high reliability</em>.” This data can thus be used to train, fit, and test a suitable algorithm for the department of human services.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>high_reliability <span class="ot">&lt;-</span> county_summary <span class="sc">|&gt;</span> </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(reliability <span class="sc">==</span> <span class="st">"High"</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(high_reliability,</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"County"</span>, <span class="st">"Median Income"</span>, <span class="st">"MOE"</span>, <span class="st">"Reliability"</span>, <span class="st">"Recommendation"</span>),</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="fu">toupper</span>(<span class="st">"NY Counties with High Reliability"</span>),</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">format.args =</span> <span class="fu">list</span>(<span class="at">big.mark =</span> <span class="st">","</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>NY COUNTIES WITH HIGH RELIABILITY</caption>
<colgroup>
<col style="width: 17%">
<col style="width: 18%">
<col style="width: 6%">
<col style="width: 16%">
<col style="width: 41%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: right;">Median Income</th>
<th style="text-align: right;">MOE</th>
<th style="text-align: left;">Reliability</th>
<th style="text-align: left;">Recommendation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Queens</td>
<td style="text-align: right;">82,431</td>
<td style="text-align: right;">1.06</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Erie</td>
<td style="text-align: right;">68,014</td>
<td style="text-align: right;">1.18</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Suffolk</td>
<td style="text-align: right;">122,498</td>
<td style="text-align: right;">1.18</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kings</td>
<td style="text-align: right;">74,692</td>
<td style="text-align: right;">1.27</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Monroe</td>
<td style="text-align: right;">71,450</td>
<td style="text-align: right;">1.35</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nassau</td>
<td style="text-align: right;">137,709</td>
<td style="text-align: right;">1.39</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Westchester</td>
<td style="text-align: right;">114,651</td>
<td style="text-align: right;">1.56</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Onondaga</td>
<td style="text-align: right;">71,479</td>
<td style="text-align: right;">1.57</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">New York</td>
<td style="text-align: right;">99,880</td>
<td style="text-align: right;">1.78</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bronx</td>
<td style="text-align: right;">47,036</td>
<td style="text-align: right;">1.89</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Orange</td>
<td style="text-align: right;">91,806</td>
<td style="text-align: right;">1.94</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Saratoga</td>
<td style="text-align: right;">97,038</td>
<td style="text-align: right;">2.26</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rensselaer</td>
<td style="text-align: right;">83,734</td>
<td style="text-align: right;">2.27</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Albany</td>
<td style="text-align: right;">78,829</td>
<td style="text-align: right;">2.60</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Richmond</td>
<td style="text-align: right;">96,185</td>
<td style="text-align: right;">2.60</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dutchess</td>
<td style="text-align: right;">94,578</td>
<td style="text-align: right;">2.66</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Niagara</td>
<td style="text-align: right;">65,882</td>
<td style="text-align: right;">2.67</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Steuben</td>
<td style="text-align: right;">62,506</td>
<td style="text-align: right;">2.87</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rockland</td>
<td style="text-align: right;">106,173</td>
<td style="text-align: right;">2.88</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ontario</td>
<td style="text-align: right;">76,603</td>
<td style="text-align: right;">2.94</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Broome</td>
<td style="text-align: right;">58,317</td>
<td style="text-align: right;">3.02</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Schenectady</td>
<td style="text-align: right;">75,056</td>
<td style="text-align: right;">3.03</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wayne</td>
<td style="text-align: right;">71,007</td>
<td style="text-align: right;">3.10</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cattaraugus</td>
<td style="text-align: right;">56,889</td>
<td style="text-align: right;">3.13</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chautauqua</td>
<td style="text-align: right;">54,625</td>
<td style="text-align: right;">3.21</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Oswego</td>
<td style="text-align: right;">65,054</td>
<td style="text-align: right;">3.26</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Oneida</td>
<td style="text-align: right;">66,402</td>
<td style="text-align: right;">3.27</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Allegany</td>
<td style="text-align: right;">58,725</td>
<td style="text-align: right;">3.35</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wyoming</td>
<td style="text-align: right;">65,066</td>
<td style="text-align: right;">3.38</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Columbia</td>
<td style="text-align: right;">81,741</td>
<td style="text-align: right;">3.39</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Washington</td>
<td style="text-align: right;">68,703</td>
<td style="text-align: right;">3.41</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">St.&nbsp;Lawrence</td>
<td style="text-align: right;">58,339</td>
<td style="text-align: right;">3.47</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Montgomery</td>
<td style="text-align: right;">58,033</td>
<td style="text-align: right;">3.63</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jefferson</td>
<td style="text-align: right;">62,782</td>
<td style="text-align: right;">3.64</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Delaware</td>
<td style="text-align: right;">58,338</td>
<td style="text-align: right;">3.67</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Schoharie</td>
<td style="text-align: right;">71,479</td>
<td style="text-align: right;">3.96</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Livingston</td>
<td style="text-align: right;">70,443</td>
<td style="text-align: right;">3.99</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tioga</td>
<td style="text-align: right;">70,427</td>
<td style="text-align: right;">3.99</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tompkins</td>
<td style="text-align: right;">69,995</td>
<td style="text-align: right;">4.01</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chemung</td>
<td style="text-align: right;">61,358</td>
<td style="text-align: right;">4.03</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Putnam</td>
<td style="text-align: right;">120,970</td>
<td style="text-align: right;">4.03</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Madison</td>
<td style="text-align: right;">68,869</td>
<td style="text-align: right;">4.04</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chenango</td>
<td style="text-align: right;">61,741</td>
<td style="text-align: right;">4.09</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lewis</td>
<td style="text-align: right;">64,401</td>
<td style="text-align: right;">4.16</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Clinton</td>
<td style="text-align: right;">67,097</td>
<td style="text-align: right;">4.18</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cayuga</td>
<td style="text-align: right;">63,227</td>
<td style="text-align: right;">4.33</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sullivan</td>
<td style="text-align: right;">67,841</td>
<td style="text-align: right;">4.35</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fulton</td>
<td style="text-align: right;">60,557</td>
<td style="text-align: right;">4.37</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cortland</td>
<td style="text-align: right;">65,029</td>
<td style="text-align: right;">4.42</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Otsego</td>
<td style="text-align: right;">65,778</td>
<td style="text-align: right;">4.51</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ulster</td>
<td style="text-align: right;">77,197</td>
<td style="text-align: right;">4.52</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Genesee</td>
<td style="text-align: right;">68,178</td>
<td style="text-align: right;">4.57</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Warren</td>
<td style="text-align: right;">74,531</td>
<td style="text-align: right;">4.74</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Herkimer</td>
<td style="text-align: right;">68,104</td>
<td style="text-align: right;">4.79</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Franklin</td>
<td style="text-align: right;">60,270</td>
<td style="text-align: right;">4.81</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Orleans</td>
<td style="text-align: right;">61,069</td>
<td style="text-align: right;">4.89</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
</tbody>
</table>
</div>
</div></li>
<li><p><strong>Counties requiring additional oversight:</strong> [List counties with moderate confidence data and describe what kind of monitoring would be needed]</p>
<p>The 5 counties below have MOE percentages of between 5-10%, hence we classify the income data as having “<em>moderate reliability</em>.” Oversight measures may include periodic monitoring of outcome distributions, bias audits against protected groups, and sensitivity testing to ensure model decisions remain robust when confidence intervals shift.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>moderate_reliability <span class="ot">&lt;-</span> county_summary <span class="sc">|&gt;</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(reliability <span class="sc">==</span> <span class="st">"Moderate"</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(moderate_reliability,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"County"</span>, <span class="st">"Median Income"</span>, <span class="st">"MOE"</span>, <span class="st">"Reliability"</span>, <span class="st">"Recommendation"</span>),</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="fu">toupper</span>(<span class="st">"NY Counties with Moderate Reliability"</span>),</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">format.args =</span> <span class="fu">list</span>(<span class="at">big.mark =</span> <span class="st">","</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>NY COUNTIES WITH MODERATE RELIABILITY</caption>
<colgroup>
<col style="width: 11%">
<col style="width: 18%">
<col style="width: 6%">
<col style="width: 15%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: right;">Median Income</th>
<th style="text-align: right;">MOE</th>
<th style="text-align: left;">Reliability</th>
<th style="text-align: left;">Recommendation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Seneca</td>
<td style="text-align: right;">64,050</td>
<td style="text-align: right;">5.24</td>
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Essex</td>
<td style="text-align: right;">68,090</td>
<td style="text-align: right;">5.27</td>
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Yates</td>
<td style="text-align: right;">63,974</td>
<td style="text-align: right;">5.84</td>
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Greene</td>
<td style="text-align: right;">70,294</td>
<td style="text-align: right;">6.18</td>
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Schuyler</td>
<td style="text-align: right;">61,316</td>
<td style="text-align: right;">9.49</td>
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
</tbody>
</table>
</div>
</div></li>
<li><p><strong>Counties needing alternative approaches:</strong> [List counties with low confidence data and suggest specific alternatives - manual review, additional surveys, etc.]</p>
<p>Only 1 NY County - Hamilton County - has a MOE percentage &gt;10%, hence we classify the income data as having “<em>low reliability</em>.” Given the unreliability of this data, it is not suitable for direct algorithmic implementation. Instead, the department should rely on manual review, locally administered surveys, or integration of administrative datasets as proxies (e.g., tax records, school enrollment, social services data) to supplement ACS estimates. This ensures decisions affecting communities in Hamilton County are based on reliable, context-specific evidence rather than unreliable model inputs.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>low_reliability <span class="ot">&lt;-</span> county_summary <span class="sc">|&gt;</span> </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(reliability <span class="sc">==</span> <span class="st">"Low"</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(low_reliability,</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"County"</span>, <span class="st">"Median Income"</span>, <span class="st">"MOE"</span>, <span class="st">"Reliability"</span>, <span class="st">"Recommendation"</span>),</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="fu">toupper</span>(<span class="st">"NY Counties with Low Reliability"</span>),</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">format.args =</span> <span class="fu">list</span>(<span class="at">big.mark =</span> <span class="st">","</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>NY COUNTIES WITH LOW RELIABILITY</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 16%">
<col style="width: 7%">
<col style="width: 14%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: right;">Median Income</th>
<th style="text-align: right;">MOE</th>
<th style="text-align: left;">Reliability</th>
<th style="text-align: left;">Recommendation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Hamilton</td>
<td style="text-align: right;">66,891</td>
<td style="text-align: right;">11.39</td>
<td style="text-align: left;">Low</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
</tbody>
</table>
</div>
</div></li>
</ol>
</section>
<section id="questions-for-further-investigation" class="level2">
<h2 class="anchored" data-anchor-id="questions-for-further-investigation">Questions for Further Investigation</h2>
<p>[List 2-3 questions that your analysis raised that you’d like to explore further in future assignments. Consider questions about spatial patterns, time trends, or other demographic factors.]</p>
<ol type="1">
<li>How MOEs for population data at the census tract level are estimated and computed, given that MOEs for population data at the county level are not reported because there are various other proxies that can help to create a reliable population estimate</li>
<li>How have MOEs changed over time for ACS data – i.e.&nbsp;has there been any improvements in methods and reporting over the years? In addition, how should we think about MOEs for other important datasets, such as the annual homelessness point-in-time (PIT) counts?</li>
<li>How can we map and visualize these tibbles effectively in R, without having to export our data tables to ArcGIS?</li>
</ol>
</section>
</section>
<section id="technical-notes" class="level1">
<h1>Technical Notes</h1>
<p><strong>Data Sources:</strong> - U.S. Census Bureau, American Community Survey 2018-2022 5-Year Estimates - Retrieved via tidycensus R package on September 23, 2025</p>
<p><strong>Reproducibility:</strong> - All analysis conducted in R version 4.5.1 - Census API key required for replication - Complete code and documentation available at: <a href="https://musa-5080-fall-2025.github.io/portfolio-setup-jedchewjm/" class="uri">https://musa-5080-fall-2025.github.io/portfolio-setup-jedchewjm/</a></p>
<p><strong>Methodology Notes:</strong> - There are no significant decisions that I made that might affect reproducibility - I selected my three counties of Hamilton, Queens, and Seneca as they each represent different reliability levels (e.g., 1 high confidence, 1 moderate, 1 low confidence)</p>
<p><strong>Limitations:</strong> - given the task of implementing an algorithmic system to identify communities that should receive priority for social service funding and outreach programs, this analysis is too limited in temporal and geographic scope to provide a comprehensive recommendation - for example, this analysis only utilizes 2018-22 ACS estimates, and is unable to show how the demographic and income indicators in various communities have changed over time</p>
<hr>
<section id="submission-checklist" class="level2">
<h2 class="anchored" data-anchor-id="submission-checklist">Submission Checklist</h2>
<p>Before submitting your portfolio link on Canvas:</p>
<ul class="task-list">
<li><label><input type="checkbox" checked="">All code chunks run without errors</label></li>
<li><label><input type="checkbox" checked="">All “[Fill this in]” prompts have been completed</label></li>
<li><label><input type="checkbox" checked="">Tables are properly formatted and readable</label></li>
<li><label><input type="checkbox" checked="">Executive summary addresses all four required components</label></li>
<li><label><input type="checkbox" checked="">Portfolio navigation includes this assignment</label></li>
<li><label><input type="checkbox" checked="">Census API key is properly set</label></li>
<li><label><input type="checkbox" checked="">Document renders correctly to HTML</label></li>
</ul>
<p><strong>Remember:</strong> Submit your portfolio URL on Canvas, not the file itself. Your assignment should be accessible at <code>your-portfolio-url/assignments/assignment_1/your_file_name.html</code></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>